.TH "libsrc Directory Reference" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libsrc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcfortran\&.h\fP"
.br
.ti -1c
.RI "file \fBfort\-attio\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-control\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-dim\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-genatt\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-geninq\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-genvar\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-lib\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-lib\&.h\fP"
.br
.ti -1c
.RI "file \fBfort\-misc\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-nc4\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-v2compat\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-var1io\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-varaio\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-vario\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-varmio\&.c\fP"
.br
.ti -1c
.RI "file \fBfort\-varsio\&.c\fP"
.br
.ti -1c
.RI "file \fBncfortran\&.h\fP"
.br
.ti -1c
.RI "file \fBnetcdf_f\&.h\fP"
.br
.in -1c
