.TH "f90_The-NetCDF-Fortran-90-Interface-Guide" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f90_The-NetCDF-Fortran-90-Interface-GuideThe NetCDF Fortran 90 Interface Guide 
 \- This document describes the Fortran 90 interface to the netCDF library\&.
.PP
You can use the netCDF library without knowing about all of the netCDF interface\&. If you are creating a netCDF dataset, only a handful of routines are required to define the necessary dimensions, variables, and attributes, and to write the data to the netCDF dataset\&. Similarly, if you are writing software to access data stored in a particular netCDF object, only a small subset of the netCDF library is required to open the netCDF dataset and access the data\&. Authors of generic applications that access arbitrary netCDF datasets need to be familiar with more of the netCDF library\&.
.PP
.IP "\(bu" 2
\fB1 Use of the NetCDF Library\fP
.IP "\(bu" 2
\fB2 Datasets\fP
.IP "\(bu" 2
\fB3 Groups\fP
.IP "\(bu" 2
\fB4 Dimensions\fP
.IP "\(bu" 2
\fB5 User Defined Data Types\fP
.IP "\(bu" 2
\fB6 Variables\fP
.IP "\(bu" 2
\fB7 Attributes\fP 
.PP

