.TH "fort-control.c" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort-control.c
.SH SYNOPSIS
.br
.PP
\fC#include <config\&.h>\fP
.br
\fC#include 'netcdf\&.h'\fP
.br
\fC#include 'ncfortran\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
