.TH "fort-lib.h" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort-lib.h
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include 'ncfortran\&.h'\fP
.br
\fC#include <netcdf_f\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "EXTERNL \fBNF_INTEGER\fP * \fBc2f_dimids\fP (int ncid, int varid, const int *cdimids, \fBNF_INTEGER\fP *fdimids)"
.br
.ti -1c
.RI "EXTERNL int * \fBf2c_dimids\fP (int ndims, const \fBNF_INTEGER\fP *fdimids, int *cdimids)"
.br
.ti -1c
.RI "EXTERNL \fBNF_INTEGER\fP * \fBc2f_chunksizes\fP (int ncid, int varid, const int *cchunksizes, \fBNF_INTEGER\fP *fchunksizes)"
.br
.ti -1c
.RI "EXTERNL int * \fBf2c_chunksizes\fP (int ncid, int varid, const \fBNF_INTEGER\fP *fchunksizes, int *cchunksizes)"
.br
.ti -1c
.RI "EXTERNL size_t * \fBf2c_coords\fP (int ncid, int varid, const \fBNF_INTEGER\fP *fcoords, size_t *ccoords)"
.br
.ti -1c
.RI "EXTERNL size_t * \fBf2c_counts\fP (int ncid, int varid, const \fBNF_INTEGER\fP *fcounts, size_t *ccounts)"
.br
.ti -1c
.RI "EXTERNL ptrdiff_t * \fBf2c_strides\fP (int ncid, int varid, const \fBNF_INTEGER\fP *fstrides, ptrdiff_t *cstrides)"
.br
.ti -1c
.RI "EXTERNL ptrdiff_t * \fBf2c_maps\fP (int ncid, int varid, const \fBNF_INTEGER\fP *fmaps, ptrdiff_t *cmaps)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "EXTERNL \fBNF_INTEGER\fP* c2f_chunksizes (int ncid, int varid, const int * cchunksizes, \fBNF_INTEGER\fP * fchunksizes)"

.PP
Definition at line 52 of file fort\-lib\&.c\&.
.SS "EXTERNL \fBNF_INTEGER\fP* c2f_dimids (int ncid, int varid, const int * cdimids, \fBNF_INTEGER\fP * fdimids)"

.PP
Definition at line 22 of file fort\-lib\&.c\&.
.SS "EXTERNL int* f2c_chunksizes (int ncid, int varid, const \fBNF_INTEGER\fP * fchunksizes, int * cchunksizes)"

.PP
Definition at line 68 of file fort\-lib\&.c\&.
.SS "EXTERNL size_t* f2c_coords (int ncid, int varid, const \fBNF_INTEGER\fP * fcoords, size_t * ccoords)"

.PP
Definition at line 86 of file fort\-lib\&.c\&.
.SS "EXTERNL size_t* f2c_counts (int ncid, int varid, const \fBNF_INTEGER\fP * fcounts, size_t * ccounts)"

.PP
Definition at line 106 of file fort\-lib\&.c\&.
.SS "EXTERNL int* f2c_dimids (int ndims, const \fBNF_INTEGER\fP * fdimids, int * cdimids)"

.PP
Definition at line 40 of file fort\-lib\&.c\&.
.SS "EXTERNL ptrdiff_t* f2c_maps (int ncid, int varid, const \fBNF_INTEGER\fP * fmaps, ptrdiff_t * cmaps)"

.PP
Definition at line 148 of file fort\-lib\&.c\&.
.SS "EXTERNL ptrdiff_t* f2c_strides (int ncid, int varid, const \fBNF_INTEGER\fP * fstrides, ptrdiff_t * cstrides)"

.PP
Definition at line 128 of file fort\-lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
