.TH "fort-misc.c" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort-misc.c
.SH SYNOPSIS
.br
.PP
\fC#include <config\&.h>\fP
.br
\fC#include 'netcdf\&.h'\fP
.br
\fC#include 'ncfortran\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFCALLSCFUN1\fP (STRING,(char *) nc_strerror, NF_STRERROR, \fBnf_strerror\fP, FINT2CINT) static int nc_issyserr(int errcode)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FCALLSCFUN1 (STRING, (char *) nc_strerror, NF_STRERROR, \fBnf_strerror\fP, FINT2CINT)"

.PP
Definition at line 36 of file fort\-misc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
