.TH "ncfortran.h" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ncfortran.h
.SH SYNOPSIS
.br
.PP
\fC#include 'netcdf_f\&.h'\fP
.br
\fC#include 'cfortran\&.h'\fP
.br
\fC#include 'nfconfig\&.inc'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNF_INTEGER\fP   int"
.br
.ti -1c
.RI "#define \fBNF_INT\fP   INT"
.br
.ti -1c
.RI "#define \fBFINT2CINT_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBFINT2CINT_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBFINT2CINT_cfN\fP( T,  A)   const \fBNF_INTEGER\fP *A"
.br
.ti -1c
.RI "#define \fBFINT2CINT_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBFINT2CINT_cfT\fP(M,  I,  A,  B,  D)   (int)*A"
.br
.ti -1c
.RI "#define \fBFINT2CSIZET_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBFINT2CSIZET_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBFINT2CSIZET_cfN\fP( T,  A)   const \fBNF_INTEGER\fP *A"
.br
.ti -1c
.RI "#define \fBFINT2CSIZET_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBFINT2CSIZET_cfT\fP(M,  I,  A,  B,  D)   (size_t)*A"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZEHINT_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZEHINT_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZEHINT_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,PCHUNKSIZEHINT,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZEHINT_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZEHINT_cfQ\fP(B)   size_t B;"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZEHINT_cfT\fP(M,  I,  A,  B,  D)   ((void*)(B=*A), &B)"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZEHINT_cfR\fP(A,  B,  D)   *A=B;"
.br
.ti -1c
.RI "#define \fBPCINT2FINT_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPCINT2FINT_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBPCINT2FINT_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,PCINT2FINT,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPCINT2FINT_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBPCINT2FINT_cfQ\fP(B)   int B;"
.br
.ti -1c
.RI "#define \fBPCINT2FINT_cfT\fP(M,  I,  A,  B,  D)   &B"
.br
.ti -1c
.RI "#define \fBPCINT2FINT_cfR\fP(A,  B,  D)   *A=B;"
.br
.ti -1c
.RI "#define \fBFNDX2CNDX_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBFNDX2CNDX_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBFNDX2CNDX_cfN\fP( T,  A)   const \fBNF_INTEGER\fP *A"
.br
.ti -1c
.RI "#define \fBFNDX2CNDX_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBFNDX2CNDX_cfT\fP(M,  I,  A,  B,  D)   (*A\-1)"
.br
.ti -1c
.RI "#define \fBPCNDX2FNDX_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPCNDX2FNDX_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBPCNDX2FNDX_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,PCNDX2FNDX,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPCNDX2FNDX_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBPCNDX2FNDX_cfQ\fP(B)   int B;"
.br
.ti -1c
.RI "#define \fBPCNDX2FNDX_cfT\fP(M,  I,  A,  B,  D)   &B"
.br
.ti -1c
.RI "#define \fBPCNDX2FNDX_cfR\fP(A,  B,  D)   *A=B+1;"
.br
.ti -1c
.RI "#define \fBCBUF_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSTRING_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBCBUF_cfSEP\fP(T,  B)   \fBSTRING_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBCBUF_cfN\fP( T,  A)   \fBSTRING_cfN\fP(T,A)"
.br
.ti -1c
.RI "#define \fBCBUF_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSTRING_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBCBUF_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBTEXTATT\fP   STRING"
.br
.ti -1c
.RI "#define \fBPTEXTATT\fP   PSTRING"
.br
.ti -1c
.RI "#define \fBINT1ATT\fP   \fBINT1VARV\fP"
.br
.ti -1c
.RI "#define \fBPINT1ATT\fP   \fBPINT1VARV\fP"
.br
.ti -1c
.RI "#define \fBINT2ATT\fP   \fBINT2VARV\fP"
.br
.ti -1c
.RI "#define \fBPINT2ATT\fP   \fBPINT2VARV\fP"
.br
.ti -1c
.RI "#define \fBINTATT\fP   \fBINTVARV\fP"
.br
.ti -1c
.RI "#define \fBPINTATT\fP   \fBPINTVARV\fP"
.br
.ti -1c
.RI "#define \fBREALATT\fP   \fBREALVARV\fP"
.br
.ti -1c
.RI "#define \fBPREALATT\fP   \fBPREALVARV\fP"
.br
.ti -1c
.RI "#define \fBDOUBLEATT\fP   \fBDOUBLEVARV\fP"
.br
.ti -1c
.RI "#define \fBPDOUBLEATT\fP   \fBPDOUBLEVARV\fP"
.br
.ti -1c
.RI "#define \fBATTID\fP   FNDX2CNDX"
.br
.ti -1c
.RI "#define \fBPATTID\fP   PCNDX2FNDX"
.br
.ti -1c
.RI "#define \fBTYPE_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBTYPE_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBTYPE_cfN\fP( T,  A)   \fBNF_INTEGER\fP *A"
.br
.ti -1c
.RI "#define \fBTYPE_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBTYPE_cfT\fP(M,  I,  A,  B,  D)   ((nc_type)*A)"
.br
.ti -1c
.RI "#define \fBPTYPE_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPTYPE_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBPTYPE_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,PTYPE,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPTYPE_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBPTYPE_cfQ\fP(B)   nc_type B;"
.br
.ti -1c
.RI "#define \fBPTYPE_cfT\fP(M,  I,  A,  B,  D)   &B"
.br
.ti -1c
.RI "#define \fBPTYPE_cfR\fP(A,  B,  D)   *A=B;"
.br
.ti -1c
.RI "#define \fBNDIMS_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBNDIMS_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBNDIMS_cfN\fP( T,  A)   \fBNF_INTEGER\fP *fndims"
.br
.ti -1c
.RI "#define \fBNDIMS_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBNDIMS_cfT\fP(M,  I,  A,  B,  D)   ((int)*fndims)"
.br
.ti -1c
.RI "#define \fBPNDIMS\fP   PCINT2FINT"
.br
.ti -1c
.RI "#define \fBNVARS\fP   FINT2CINT"
.br
.ti -1c
.RI "#define \fBPNVARS\fP   \fBPNDIMS\fP"
.br
.ti -1c
.RI "#define \fBNATTS\fP   FINT2CINT"
.br
.ti -1c
.RI "#define \fBPNATTS\fP   \fBPNDIMS\fP"
.br
.ti -1c
.RI "#define \fBPFORMAT\fP   \fBPNDIMS\fP"
.br
.ti -1c
.RI "#define \fBTEXTVAR\fP   STRING"
.br
.ti -1c
.RI "#define \fBPTEXTVAR\fP   PSTRING"
.br
.ti -1c
.RI "#define \fBTEXTVARV\fP   STRING"
.br
.ti -1c
.RI "#define \fBPTEXTVARV\fP   PSTRING"
.br
.ti -1c
.RI "#define \fBINT1VAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBINT1VAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBINT1VAR_cfN\fP( T,  A)   const signed char *A"
.br
.ti -1c
.RI "#define \fBINT1VAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBINT1VAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBPINT1VAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPINT1VAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBPINT1VAR_cfN\fP( T,  A)   signed char *A"
.br
.ti -1c
.RI "#define \fBPINT1VAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPINT1VAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBINT1VARV\fP   INT1VAR"
.br
.ti -1c
.RI "#define \fBPINT1VARV\fP   PINT1VAR"
.br
.ti -1c
.RI "#define \fBINT2VAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBINT2VAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBINT2VAR_cfN\fP( T,  A)   const short *A"
.br
.ti -1c
.RI "#define \fBINT2VAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBINT2VAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBPINT2VAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPINT2VAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBPINT2VAR_cfN\fP( T,  A)   short *A"
.br
.ti -1c
.RI "#define \fBPINT2VAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPINT2VAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBINT2VARV\fP   INT2VAR"
.br
.ti -1c
.RI "#define \fBPINT2VARV\fP   PINT2VAR"
.br
.ti -1c
.RI "#define \fBINTVAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBINTVAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBINTVAR_cfN\fP( T,  A)   const \fBNF_INTEGER\fP *A"
.br
.ti -1c
.RI "#define \fBINTVAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBINTVAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBPINTVAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPINTVAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBPINTVAR_cfN\fP( T,  A)   \fBNF_INTEGER\fP *A"
.br
.ti -1c
.RI "#define \fBPINTVAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPINTVAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBINTVARV\fP   INTVAR"
.br
.ti -1c
.RI "#define \fBPINTVARV\fP   PINTVAR"
.br
.ti -1c
.RI "#define \fBREALVAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBREALVAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBREALVAR_cfN\fP( T,  A)   const float *A"
.br
.ti -1c
.RI "#define \fBREALVAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBREALVAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBPREALVAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPREALVAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBPREALVAR_cfN\fP( T,  A)   float *A"
.br
.ti -1c
.RI "#define \fBPREALVAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPREALVAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBREALVARV\fP   REALVAR"
.br
.ti -1c
.RI "#define \fBPREALVARV\fP   PREALVAR"
.br
.ti -1c
.RI "#define \fBDOUBLEVAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBDOUBLEVAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBDOUBLEVAR_cfN\fP( T,  A)   const double *A"
.br
.ti -1c
.RI "#define \fBDOUBLEVAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBDOUBLEVAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBPDOUBLEVAR_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPDOUBLEVAR_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBPDOUBLEVAR_cfN\fP( T,  A)   double *A"
.br
.ti -1c
.RI "#define \fBPDOUBLEVAR_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPDOUBLEVAR_cfT\fP(M,  I,  A,  B,  D)   A"
.br
.ti -1c
.RI "#define \fBDOUBLEVARV\fP   DOUBLEVAR"
.br
.ti -1c
.RI "#define \fBPDOUBLEVARV\fP   PDOUBLEVAR"
.br
.ti -1c
.RI "#define \fBPSIZET_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPSIZET_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBPSIZET_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,PSIZET,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPSIZET_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBPSIZET_cfQ\fP(B)   size_t B;"
.br
.ti -1c
.RI "#define \fBPSIZET_cfT\fP(M,  I,  A,  B,  D)   &B"
.br
.ti -1c
.RI "#define \fBPSIZET_cfR\fP(A,  B,  D)   *A=B;"
.br
.ti -1c
.RI "#define \fBDIMID\fP   FNDX2CNDX"
.br
.ti -1c
.RI "#define \fBPDIMID_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPDIMID_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBPDIMID_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,PDIMID,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPDIMID_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBPDIMID_cfQ\fP(B)   int B = \-1;"
.br
.ti -1c
.RI "#define \fBPDIMID_cfT\fP(M,  I,  A,  B,  D)   &B"
.br
.ti -1c
.RI "#define \fBPDIMID_cfR\fP(A,  B,  D)   *A=(B == \-1 ? \-1 : B+1);"
.br
.ti -1c
.RI "#define \fBDIMIDS_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBDIMIDSVVVVVVV_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBDIMIDS_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,DIMIDS,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBDIMIDS_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBDIMIDS_cfQ\fP(B)   int B[NC_MAX_DIMS];"
.br
.ti -1c
.RI "#define \fBDIMIDS_cfT\fP(M,  I,  A,  B,  D)   \fBf2c_dimids\fP(*fndims, A, B)"
.br
.ti -1c
.RI "#define \fBDIMIDS_cfR\fP(A,  B,  D)"
.br
.ti -1c
.RI "#define \fBPDIMIDS_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPDIMIDS_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBPDIMIDS_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,PDIMIDS,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPDIMIDS_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBPDIMIDS_cfQ\fP(B)   int B[NC_MAX_DIMS];"
.br
.ti -1c
.RI "#define \fBPDIMIDS_cfT\fP(M,  I,  A,  B,  D)   B"
.br
.ti -1c
.RI "#define \fBPDIMIDS_cfR\fP(A,  B,  D)   \fBc2f_dimids\fP(*fncid, *fvarid\-1, B, A);"
.br
.ti -1c
.RI "#define \fBCHUNKSIZES_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBCHUNKSIZESVVVVVVV_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBCHUNKSIZES_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,CHUNKSIZES,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBCHUNKSIZES_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBCHUNKSIZES_cfQ\fP(B)   int B[NC_MAX_DIMS];"
.br
.ti -1c
.RI "#define \fBCHUNKSIZES_cfT\fP(M,  I,  A,  B,  D)   \fBf2c_chunksizes\fP(*fncid, *fvarid\-1, A, B)"
.br
.ti -1c
.RI "#define \fBCHUNKSIZES_cfR\fP(A,  B,  D)"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZES_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZES_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZES_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,PCHUNKSIZES,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZES_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZES_cfQ\fP(B)   int B[NC_MAX_DIMS];"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZES_cfT\fP(M,  I,  A,  B,  D)   B"
.br
.ti -1c
.RI "#define \fBPCHUNKSIZES_cfR\fP(A,  B,  D)   \fBc2f_chunksizes\fP(*fncid, *fvarid\-1, B, A);"
.br
.ti -1c
.RI "#define \fBNCID_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBNCID_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBNCID_cfN\fP( T,  A)   \fBNF_INTEGER\fP *fncid"
.br
.ti -1c
.RI "#define \fBNCID_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBNCID_cfT\fP(M,  I,  A,  B,  D)   *fncid"
.br
.ti -1c
.RI "#define \fBNCID1\fP   FINT2CINT"
.br
.ti -1c
.RI "#define \fBNCID2\fP   FINT2CINT"
.br
.ti -1c
.RI "#define \fBPNCID\fP   PCINT2FINT"
.br
.ti -1c
.RI "#define \fBVARID_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBVARID_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBVARID_cfN\fP( T,  A)   \fBNF_INTEGER\fP *fvarid"
.br
.ti -1c
.RI "#define \fBVARID_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBVARID_cfT\fP(M,  I,  A,  B,  D)   (*fvarid\-1)"
.br
.ti -1c
.RI "#define \fBVARID1_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBVARID1_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBVARID1_cfN\fP( T,  A)   \fBNF_INTEGER\fP *fvarid1"
.br
.ti -1c
.RI "#define \fBVARID1_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBVARID1_cfT\fP(M,  I,  A,  B,  D)   (*fvarid1\-1)"
.br
.ti -1c
.RI "#define \fBVARID2_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBVARID2_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBVARID2_cfN\fP( T,  A)   \fBNF_INTEGER\fP *fvarid2"
.br
.ti -1c
.RI "#define \fBVARID2_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBVARID2_cfT\fP(M,  I,  A,  B,  D)   (*fvarid2\-1)"
.br
.ti -1c
.RI "#define \fBPVARID\fP   PCNDX2FNDX"
.br
.ti -1c
.RI "#define \fBFIELDIDX_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBFIELDIDX_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBFIELDIDX_cfN\fP( T,  A)   \fBNF_INTEGER\fP *ffieldidx"
.br
.ti -1c
.RI "#define \fBFIELDIDX_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBFIELDIDX_cfT\fP(M,  I,  A,  B,  D)   (*ffieldidx\-1)"
.br
.ti -1c
.RI "#define \fBCOORDS_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBCOORDSVVVVVVV_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBCOORDS_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,COORDS,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBCOORDS_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBCOORDS_cfQ\fP(B)   size_t B[NC_MAX_DIMS];"
.br
.ti -1c
.RI "#define \fBCOORDS_cfT\fP(M,  I,  A,  B,  D)   \fBf2c_coords\fP(*fncid, *fvarid\-1, A, B)"
.br
.ti -1c
.RI "#define \fBCOORDS_cfR\fP(A,  B,  D)"
.br
.ti -1c
.RI "#define \fBCOUNT_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBCOUNT_cfSEP\fP(T,  B)   \fBSIMPLE_cfSEP\fP(T,B)"
.br
.ti -1c
.RI "#define \fBCOUNT_cfN\fP( T,  A)   const \fBNF_INTEGER\fP *A"
.br
.ti -1c
.RI "#define \fBCOUNT_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBCOUNT_cfT\fP(M,  I,  A,  B,  D)   (size_t)*A"
.br
.ti -1c
.RI "#define \fBPCOUNT\fP   PSIZET"
.br
.ti -1c
.RI "#define \fBCOUNTS_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBCOUNTSVVVVVVV_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBCOUNTS_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,COUNTS,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBCOUNTS_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBCOUNTS_cfQ\fP(B)   size_t B[NC_MAX_DIMS];"
.br
.ti -1c
.RI "#define \fBCOUNTS_cfT\fP(M,  I,  A,  B,  D)   \fBf2c_counts\fP(*fncid, *fvarid\-1, A, B)"
.br
.ti -1c
.RI "#define \fBCOUNTS_cfR\fP(A,  B,  D)"
.br
.ti -1c
.RI "#define \fBSTRIDES_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBSTRIDESVVVVVVV_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBSTRIDES_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,STRIDES,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBSTRIDES_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBSTRIDES_cfQ\fP(B)   ptrdiff_t B[NC_MAX_DIMS];"
.br
.ti -1c
.RI "#define \fBSTRIDES_cfT\fP(M,  I,  A,  B,  D)   \fBf2c_strides\fP(*fncid, *fvarid\-1, A, B)"
.br
.ti -1c
.RI "#define \fBSTRIDES_cfR\fP(A,  B,  D)"
.br
.ti -1c
.RI "#define \fBMAPS_cfINT\fP(N,  A,  B,  X,  Y,  Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"
.br
.ti -1c
.RI "#define \fBMAPSVVVVVVV_cfTYPE\fP   \fBNF_INTEGER\fP"
.br
.ti -1c
.RI "#define \fBMAPS_cfSTR\fP(N,  T,  A,  B,  C,  D,  E)   \fB_\fP(CFARGS,N)(T,MAPS,A,B,C,D,E)"
.br
.ti -1c
.RI "#define \fBMAPS_cfH\fP(S,  U,  B)"
.br
.ti -1c
.RI "#define \fBMAPS_cfQ\fP(B)   ptrdiff_t B[NC_MAX_DIMS];"
.br
.ti -1c
.RI "#define \fBMAPS_cfT\fP(M,  I,  A,  B,  D)   \fBf2c_maps\fP(*fncid, *fvarid\-1, A, B)"
.br
.ti -1c
.RI "#define \fBMAPS_cfR\fP(A,  B,  D)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ATTID   FNDX2CNDX"

.PP
Definition at line 137 of file ncfortran\&.h\&.
.SS "#define CBUF_cfINT(N, A, B, X, Y, Z)   \fBSTRING_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 98 of file ncfortran\&.h\&.
.SS "#define CBUF_cfN(T, A)   \fBSTRING_cfN\fP(T,A)"

.PP
Definition at line 100 of file ncfortran\&.h\&.
.SS "#define CBUF_cfSEP(T, B)   \fBSTRING_cfSEP\fP(T,B)"

.PP
Definition at line 99 of file ncfortran\&.h\&.
.SS "#define CBUF_cfSTR(N, T, A, B, C, D, E)   \fBSTRING_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 101 of file ncfortran\&.h\&.
.SS "#define CBUF_cfT(M, I, A, B, D)   A"

.PP
Definition at line 107 of file ncfortran\&.h\&.
.SS "#define CHUNKSIZES_cfH(S, U, B)"

.PP
Definition at line 512 of file ncfortran\&.h\&.
.SS "#define CHUNKSIZES_cfINT(N, A, B, X, Y, Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 509 of file ncfortran\&.h\&.
.SS "#define CHUNKSIZES_cfQ(B)   int B[NC_MAX_DIMS];"

.PP
Definition at line 513 of file ncfortran\&.h\&.
.SS "#define CHUNKSIZES_cfR(A, B, D)"

.PP
Definition at line 515 of file ncfortran\&.h\&.
.SS "#define CHUNKSIZES_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,CHUNKSIZES,A,B,C,D,E)"

.PP
Definition at line 511 of file ncfortran\&.h\&.
.SS "#define CHUNKSIZES_cfT(M, I, A, B, D)   \fBf2c_chunksizes\fP(*fncid, *fvarid\-1, A, B)"

.PP
Definition at line 514 of file ncfortran\&.h\&.
.SS "#define CHUNKSIZESVVVVVVV_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 510 of file ncfortran\&.h\&.
.SS "#define COORDS_cfH(S, U, B)"

.PP
Definition at line 599 of file ncfortran\&.h\&.
.SS "#define COORDS_cfINT(N, A, B, X, Y, Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 596 of file ncfortran\&.h\&.
.SS "#define COORDS_cfQ(B)   size_t B[NC_MAX_DIMS];"

.PP
Definition at line 600 of file ncfortran\&.h\&.
.SS "#define COORDS_cfR(A, B, D)"

.PP
Definition at line 602 of file ncfortran\&.h\&.
.SS "#define COORDS_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,COORDS,A,B,C,D,E)"

.PP
Definition at line 598 of file ncfortran\&.h\&.
.SS "#define COORDS_cfT(M, I, A, B, D)   \fBf2c_coords\fP(*fncid, *fvarid\-1, A, B)"

.PP
Definition at line 601 of file ncfortran\&.h\&.
.SS "#define COORDSVVVVVVV_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 597 of file ncfortran\&.h\&.
.SS "#define COUNT_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 608 of file ncfortran\&.h\&.
.SS "#define COUNT_cfN(T, A)   const \fBNF_INTEGER\fP *A"

.PP
Definition at line 610 of file ncfortran\&.h\&.
.SS "#define COUNT_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 609 of file ncfortran\&.h\&.
.SS "#define COUNT_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 611 of file ncfortran\&.h\&.
.SS "#define COUNT_cfT(M, I, A, B, D)   (size_t)*A"

.PP
Definition at line 612 of file ncfortran\&.h\&.
.SS "#define COUNTS_cfH(S, U, B)"

.PP
Definition at line 627 of file ncfortran\&.h\&.
.SS "#define COUNTS_cfINT(N, A, B, X, Y, Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 624 of file ncfortran\&.h\&.
.SS "#define COUNTS_cfQ(B)   size_t B[NC_MAX_DIMS];"

.PP
Definition at line 628 of file ncfortran\&.h\&.
.SS "#define COUNTS_cfR(A, B, D)"

.PP
Definition at line 630 of file ncfortran\&.h\&.
.SS "#define COUNTS_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,COUNTS,A,B,C,D,E)"

.PP
Definition at line 626 of file ncfortran\&.h\&.
.SS "#define COUNTS_cfT(M, I, A, B, D)   \fBf2c_counts\fP(*fncid, *fvarid\-1, A, B)"

.PP
Definition at line 629 of file ncfortran\&.h\&.
.SS "#define COUNTSVVVVVVV_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 625 of file ncfortran\&.h\&.
.SS "#define DIMID   FNDX2CNDX"

.PP
Definition at line 468 of file ncfortran\&.h\&.
.SS "#define DIMIDS_cfH(S, U, B)"

.PP
Definition at line 489 of file ncfortran\&.h\&.
.SS "#define DIMIDS_cfINT(N, A, B, X, Y, Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 486 of file ncfortran\&.h\&.
.SS "#define DIMIDS_cfQ(B)   int B[NC_MAX_DIMS];"

.PP
Definition at line 490 of file ncfortran\&.h\&.
.SS "#define DIMIDS_cfR(A, B, D)"

.PP
Definition at line 492 of file ncfortran\&.h\&.
.SS "#define DIMIDS_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,DIMIDS,A,B,C,D,E)"

.PP
Definition at line 488 of file ncfortran\&.h\&.
.SS "#define DIMIDS_cfT(M, I, A, B, D)   \fBf2c_dimids\fP(*fndims, A, B)"

.PP
Definition at line 491 of file ncfortran\&.h\&.
.SS "#define DIMIDSVVVVVVV_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 487 of file ncfortran\&.h\&.
.SS "#define DOUBLEATT   \fBDOUBLEVARV\fP"

.PP
Definition at line 130 of file ncfortran\&.h\&.
.SS "#define DOUBLEVAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 419 of file ncfortran\&.h\&.
.SS "#define DOUBLEVAR_cfN(T, A)   const double *A"

.PP
Definition at line 421 of file ncfortran\&.h\&.
.SS "#define DOUBLEVAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 420 of file ncfortran\&.h\&.
.SS "#define DOUBLEVAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 422 of file ncfortran\&.h\&.
.SS "#define DOUBLEVAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 423 of file ncfortran\&.h\&.
.SS "#define DOUBLEVARV   DOUBLEVAR"

.PP
Definition at line 439 of file ncfortran\&.h\&.
.SS "#define FIELDIDX_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 587 of file ncfortran\&.h\&.
.SS "#define FIELDIDX_cfN(T, A)   \fBNF_INTEGER\fP *ffieldidx"

.PP
Definition at line 589 of file ncfortran\&.h\&.
.SS "#define FIELDIDX_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 588 of file ncfortran\&.h\&.
.SS "#define FIELDIDX_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 590 of file ncfortran\&.h\&.
.SS "#define FIELDIDX_cfT(M, I, A, B, D)   (*ffieldidx\-1)"

.PP
Definition at line 591 of file ncfortran\&.h\&.
.SS "#define FINT2CINT_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 30 of file ncfortran\&.h\&.
.SS "#define FINT2CINT_cfN(T, A)   const \fBNF_INTEGER\fP *A"

.PP
Definition at line 32 of file ncfortran\&.h\&.
.SS "#define FINT2CINT_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 31 of file ncfortran\&.h\&.
.SS "#define FINT2CINT_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 33 of file ncfortran\&.h\&.
.SS "#define FINT2CINT_cfT(M, I, A, B, D)   (int)*A"

.PP
Definition at line 34 of file ncfortran\&.h\&.
.SS "#define FINT2CSIZET_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 40 of file ncfortran\&.h\&.
.SS "#define FINT2CSIZET_cfN(T, A)   const \fBNF_INTEGER\fP *A"

.PP
Definition at line 42 of file ncfortran\&.h\&.
.SS "#define FINT2CSIZET_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 41 of file ncfortran\&.h\&.
.SS "#define FINT2CSIZET_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 43 of file ncfortran\&.h\&.
.SS "#define FINT2CSIZET_cfT(M, I, A, B, D)   (size_t)*A"

.PP
Definition at line 44 of file ncfortran\&.h\&.
.SS "#define FNDX2CNDX_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 75 of file ncfortran\&.h\&.
.SS "#define FNDX2CNDX_cfN(T, A)   const \fBNF_INTEGER\fP *A"

.PP
Definition at line 77 of file ncfortran\&.h\&.
.SS "#define FNDX2CNDX_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 76 of file ncfortran\&.h\&.
.SS "#define FNDX2CNDX_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 78 of file ncfortran\&.h\&.
.SS "#define FNDX2CNDX_cfT(M, I, A, B, D)   (*A\-1)"

.PP
Definition at line 79 of file ncfortran\&.h\&.
.SS "#define INT1ATT   \fBINT1VARV\fP"

.PP
Definition at line 118 of file ncfortran\&.h\&.
.SS "#define INT1VAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 255 of file ncfortran\&.h\&.
.SS "#define INT1VAR_cfN(T, A)   const signed char *A"

.PP
Definition at line 258 of file ncfortran\&.h\&.
.SS "#define INT1VAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 256 of file ncfortran\&.h\&.
.SS "#define INT1VAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 266 of file ncfortran\&.h\&.
.SS "#define INT1VAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 267 of file ncfortran\&.h\&.
.SS "#define INT1VARV   INT1VAR"

.PP
Definition at line 291 of file ncfortran\&.h\&.
.SS "#define INT2ATT   \fBINT2VARV\fP"

.PP
Definition at line 121 of file ncfortran\&.h\&.
.SS "#define INT2VAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 303 of file ncfortran\&.h\&.
.SS "#define INT2VAR_cfN(T, A)   const short *A"

.PP
Definition at line 306 of file ncfortran\&.h\&.
.SS "#define INT2VAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 304 of file ncfortran\&.h\&.
.SS "#define INT2VAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 312 of file ncfortran\&.h\&.
.SS "#define INT2VAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 313 of file ncfortran\&.h\&.
.SS "#define INT2VARV   INT2VAR"

.PP
Definition at line 335 of file ncfortran\&.h\&.
.SS "#define INTATT   \fBINTVARV\fP"

.PP
Definition at line 124 of file ncfortran\&.h\&.
.SS "#define INTVAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 347 of file ncfortran\&.h\&.
.SS "#define INTVAR_cfN(T, A)   const \fBNF_INTEGER\fP *A"

.PP
Definition at line 349 of file ncfortran\&.h\&.
.SS "#define INTVAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 348 of file ncfortran\&.h\&.
.SS "#define INTVAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 350 of file ncfortran\&.h\&.
.SS "#define INTVAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 351 of file ncfortran\&.h\&.
.SS "#define INTVARV   INTVAR"

.PP
Definition at line 367 of file ncfortran\&.h\&.
.SS "#define MAPS_cfH(S, U, B)"

.PP
Definition at line 651 of file ncfortran\&.h\&.
.SS "#define MAPS_cfINT(N, A, B, X, Y, Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 648 of file ncfortran\&.h\&.
.SS "#define MAPS_cfQ(B)   ptrdiff_t B[NC_MAX_DIMS];"

.PP
Definition at line 652 of file ncfortran\&.h\&.
.SS "#define MAPS_cfR(A, B, D)"

.PP
Definition at line 654 of file ncfortran\&.h\&.
.SS "#define MAPS_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,MAPS,A,B,C,D,E)"

.PP
Definition at line 650 of file ncfortran\&.h\&.
.SS "#define MAPS_cfT(M, I, A, B, D)   \fBf2c_maps\fP(*fncid, *fvarid\-1, A, B)"

.PP
Definition at line 653 of file ncfortran\&.h\&.
.SS "#define MAPSVVVVVVV_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 649 of file ncfortran\&.h\&.
.SS "#define NATTS   FINT2CINT"

.PP
Definition at line 209 of file ncfortran\&.h\&.
.SS "#define NCID1   FINT2CINT"

.PP
Definition at line 543 of file ncfortran\&.h\&.
.SS "#define NCID2   FINT2CINT"

.PP
Definition at line 544 of file ncfortran\&.h\&.
.SS "#define NCID_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 533 of file ncfortran\&.h\&.
.SS "#define NCID_cfN(T, A)   \fBNF_INTEGER\fP *fncid"

.PP
Definition at line 535 of file ncfortran\&.h\&.
.SS "#define NCID_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 534 of file ncfortran\&.h\&.
.SS "#define NCID_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 536 of file ncfortran\&.h\&.
.SS "#define NCID_cfT(M, I, A, B, D)   *fncid"

.PP
Definition at line 537 of file ncfortran\&.h\&.
.SS "#define NDIMS_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 181 of file ncfortran\&.h\&.
.SS "#define NDIMS_cfN(T, A)   \fBNF_INTEGER\fP *fndims"

.PP
Definition at line 183 of file ncfortran\&.h\&.
.SS "#define NDIMS_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 182 of file ncfortran\&.h\&.
.SS "#define NDIMS_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 184 of file ncfortran\&.h\&.
.SS "#define NDIMS_cfT(M, I, A, B, D)   ((int)*fndims)"

.PP
Definition at line 185 of file ncfortran\&.h\&.
.SS "#define NF_INT   INT"

.PP
Definition at line 19 of file ncfortran\&.h\&.
.SS "#define NF_INTEGER   int"

.PP
Definition at line 18 of file ncfortran\&.h\&.
.SS "#define NVARS   FINT2CINT"

.PP
Definition at line 197 of file ncfortran\&.h\&.
.SS "#define PATTID   PCNDX2FNDX"

.PP
Definition at line 143 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZEHINT_cfH(S, U, B)"

.PP
Definition at line 54 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZEHINT_cfINT(N, A, B, X, Y, Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 50 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZEHINT_cfQ(B)   size_t B;"

.PP
Definition at line 55 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZEHINT_cfR(A, B, D)   *A=B;"

.PP
Definition at line 57 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZEHINT_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,PCHUNKSIZEHINT,A,B,C,D,E)"

.PP
Definition at line 52 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZEHINT_cfT(M, I, A, B, D)   ((void*)(B=*A), &B)"

.PP
Definition at line 56 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZEHINT_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 51 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZES_cfH(S, U, B)"

.PP
Definition at line 524 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZES_cfINT(N, A, B, X, Y, Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 521 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZES_cfQ(B)   int B[NC_MAX_DIMS];"

.PP
Definition at line 525 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZES_cfR(A, B, D)   \fBc2f_chunksizes\fP(*fncid, *fvarid\-1, B, A);"

.PP
Definition at line 527 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZES_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,PCHUNKSIZES,A,B,C,D,E)"

.PP
Definition at line 523 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZES_cfT(M, I, A, B, D)   B"

.PP
Definition at line 526 of file ncfortran\&.h\&.
.SS "#define PCHUNKSIZES_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 522 of file ncfortran\&.h\&.
.SS "#define PCINT2FINT_cfH(S, U, B)"

.PP
Definition at line 66 of file ncfortran\&.h\&.
.SS "#define PCINT2FINT_cfINT(N, A, B, X, Y, Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 63 of file ncfortran\&.h\&.
.SS "#define PCINT2FINT_cfQ(B)   int B;"

.PP
Definition at line 67 of file ncfortran\&.h\&.
.SS "#define PCINT2FINT_cfR(A, B, D)   *A=B;"

.PP
Definition at line 69 of file ncfortran\&.h\&.
.SS "#define PCINT2FINT_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,PCINT2FINT,A,B,C,D,E)"

.PP
Definition at line 65 of file ncfortran\&.h\&.
.SS "#define PCINT2FINT_cfT(M, I, A, B, D)   &B"

.PP
Definition at line 68 of file ncfortran\&.h\&.
.SS "#define PCINT2FINT_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 64 of file ncfortran\&.h\&.
.SS "#define PCNDX2FNDX_cfH(S, U, B)"

.PP
Definition at line 88 of file ncfortran\&.h\&.
.SS "#define PCNDX2FNDX_cfINT(N, A, B, X, Y, Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 85 of file ncfortran\&.h\&.
.SS "#define PCNDX2FNDX_cfQ(B)   int B;"

.PP
Definition at line 89 of file ncfortran\&.h\&.
.SS "#define PCNDX2FNDX_cfR(A, B, D)   *A=B+1;"

.PP
Definition at line 91 of file ncfortran\&.h\&.
.SS "#define PCNDX2FNDX_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,PCNDX2FNDX,A,B,C,D,E)"

.PP
Definition at line 87 of file ncfortran\&.h\&.
.SS "#define PCNDX2FNDX_cfT(M, I, A, B, D)   &B"

.PP
Definition at line 90 of file ncfortran\&.h\&.
.SS "#define PCNDX2FNDX_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 86 of file ncfortran\&.h\&.
.SS "#define PCOUNT   PSIZET"

.PP
Definition at line 618 of file ncfortran\&.h\&.
.SS "#define PDIMID_cfH(S, U, B)"

.PP
Definition at line 477 of file ncfortran\&.h\&.
.SS "#define PDIMID_cfINT(N, A, B, X, Y, Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 474 of file ncfortran\&.h\&.
.SS "#define PDIMID_cfQ(B)   int B = \-1;"

.PP
Definition at line 478 of file ncfortran\&.h\&.
.SS "#define PDIMID_cfR(A, B, D)   *A=(B == \-1 ? \-1 : B+1);"

.PP
Definition at line 480 of file ncfortran\&.h\&.
.SS "#define PDIMID_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,PDIMID,A,B,C,D,E)"

.PP
Definition at line 476 of file ncfortran\&.h\&.
.SS "#define PDIMID_cfT(M, I, A, B, D)   &B"

.PP
Definition at line 479 of file ncfortran\&.h\&.
.SS "#define PDIMID_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 475 of file ncfortran\&.h\&.
.SS "#define PDIMIDS_cfH(S, U, B)"

.PP
Definition at line 501 of file ncfortran\&.h\&.
.SS "#define PDIMIDS_cfINT(N, A, B, X, Y, Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 498 of file ncfortran\&.h\&.
.SS "#define PDIMIDS_cfQ(B)   int B[NC_MAX_DIMS];"

.PP
Definition at line 502 of file ncfortran\&.h\&.
.SS "#define PDIMIDS_cfR(A, B, D)   \fBc2f_dimids\fP(*fncid, *fvarid\-1, B, A);"

.PP
Definition at line 504 of file ncfortran\&.h\&.
.SS "#define PDIMIDS_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,PDIMIDS,A,B,C,D,E)"

.PP
Definition at line 500 of file ncfortran\&.h\&.
.SS "#define PDIMIDS_cfT(M, I, A, B, D)   B"

.PP
Definition at line 503 of file ncfortran\&.h\&.
.SS "#define PDIMIDS_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 499 of file ncfortran\&.h\&.
.SS "#define PDOUBLEATT   \fBPDOUBLEVARV\fP"

.PP
Definition at line 131 of file ncfortran\&.h\&.
.SS "#define PDOUBLEVAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 429 of file ncfortran\&.h\&.
.SS "#define PDOUBLEVAR_cfN(T, A)   double *A"

.PP
Definition at line 431 of file ncfortran\&.h\&.
.SS "#define PDOUBLEVAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 430 of file ncfortran\&.h\&.
.SS "#define PDOUBLEVAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 432 of file ncfortran\&.h\&.
.SS "#define PDOUBLEVAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 433 of file ncfortran\&.h\&.
.SS "#define PDOUBLEVARV   PDOUBLEVAR"

.PP
Definition at line 445 of file ncfortran\&.h\&.
.SS "#define PFORMAT   \fBPNDIMS\fP"

.PP
Definition at line 220 of file ncfortran\&.h\&.
.SS "#define PINT1ATT   \fBPINT1VARV\fP"

.PP
Definition at line 119 of file ncfortran\&.h\&.
.SS "#define PINT1VAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 273 of file ncfortran\&.h\&.
.SS "#define PINT1VAR_cfN(T, A)   signed char *A"

.PP
Definition at line 276 of file ncfortran\&.h\&.
.SS "#define PINT1VAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 274 of file ncfortran\&.h\&.
.SS "#define PINT1VAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 284 of file ncfortran\&.h\&.
.SS "#define PINT1VAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 285 of file ncfortran\&.h\&.
.SS "#define PINT1VARV   PINT1VAR"

.PP
Definition at line 297 of file ncfortran\&.h\&.
.SS "#define PINT2ATT   \fBPINT2VARV\fP"

.PP
Definition at line 122 of file ncfortran\&.h\&.
.SS "#define PINT2VAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 319 of file ncfortran\&.h\&.
.SS "#define PINT2VAR_cfN(T, A)   short *A"

.PP
Definition at line 322 of file ncfortran\&.h\&.
.SS "#define PINT2VAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 320 of file ncfortran\&.h\&.
.SS "#define PINT2VAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 328 of file ncfortran\&.h\&.
.SS "#define PINT2VAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 329 of file ncfortran\&.h\&.
.SS "#define PINT2VARV   PINT2VAR"

.PP
Definition at line 341 of file ncfortran\&.h\&.
.SS "#define PINTATT   \fBPINTVARV\fP"

.PP
Definition at line 125 of file ncfortran\&.h\&.
.SS "#define PINTVAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 357 of file ncfortran\&.h\&.
.SS "#define PINTVAR_cfN(T, A)   \fBNF_INTEGER\fP *A"

.PP
Definition at line 359 of file ncfortran\&.h\&.
.SS "#define PINTVAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 358 of file ncfortran\&.h\&.
.SS "#define PINTVAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 360 of file ncfortran\&.h\&.
.SS "#define PINTVAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 361 of file ncfortran\&.h\&.
.SS "#define PINTVARV   PINTVAR"

.PP
Definition at line 373 of file ncfortran\&.h\&.
.SS "#define PNATTS   \fBPNDIMS\fP"

.PP
Definition at line 215 of file ncfortran\&.h\&.
.SS "#define PNCID   PCINT2FINT"

.PP
Definition at line 550 of file ncfortran\&.h\&.
.SS "#define PNDIMS   PCINT2FINT"

.PP
Definition at line 191 of file ncfortran\&.h\&.
.SS "#define PNVARS   \fBPNDIMS\fP"

.PP
Definition at line 203 of file ncfortran\&.h\&.
.SS "#define PREALATT   \fBPREALVARV\fP"

.PP
Definition at line 128 of file ncfortran\&.h\&.
.SS "#define PREALVAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 393 of file ncfortran\&.h\&.
.SS "#define PREALVAR_cfN(T, A)   float *A"

.PP
Definition at line 398 of file ncfortran\&.h\&.
.SS "#define PREALVAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 394 of file ncfortran\&.h\&.
.SS "#define PREALVAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 400 of file ncfortran\&.h\&.
.SS "#define PREALVAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 401 of file ncfortran\&.h\&.
.SS "#define PREALVARV   PREALVAR"

.PP
Definition at line 413 of file ncfortran\&.h\&.
.SS "#define PSIZET_cfH(S, U, B)"

.PP
Definition at line 459 of file ncfortran\&.h\&.
.SS "#define PSIZET_cfINT(N, A, B, X, Y, Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 456 of file ncfortran\&.h\&.
.SS "#define PSIZET_cfQ(B)   size_t B;"

.PP
Definition at line 460 of file ncfortran\&.h\&.
.SS "#define PSIZET_cfR(A, B, D)   *A=B;"

.PP
Definition at line 462 of file ncfortran\&.h\&.
.SS "#define PSIZET_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,PSIZET,A,B,C,D,E)"

.PP
Definition at line 458 of file ncfortran\&.h\&.
.SS "#define PSIZET_cfT(M, I, A, B, D)   &B"

.PP
Definition at line 461 of file ncfortran\&.h\&.
.SS "#define PSIZET_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 457 of file ncfortran\&.h\&.
.SS "#define PTEXTATT   PSTRING"

.PP
Definition at line 116 of file ncfortran\&.h\&.
.SS "#define PTEXTVAR   PSTRING"

.PP
Definition at line 237 of file ncfortran\&.h\&.
.SS "#define PTEXTVARV   PSTRING"

.PP
Definition at line 249 of file ncfortran\&.h\&.
.SS "#define PTYPE_cfH(S, U, B)"

.PP
Definition at line 167 of file ncfortran\&.h\&.
.SS "#define PTYPE_cfINT(N, A, B, X, Y, Z)   \fBPDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 164 of file ncfortran\&.h\&.
.SS "#define PTYPE_cfQ(B)   nc_type B;"

.PP
Definition at line 168 of file ncfortran\&.h\&.
.SS "#define PTYPE_cfR(A, B, D)   *A=B;"

.PP
Definition at line 170 of file ncfortran\&.h\&.
.SS "#define PTYPE_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,PTYPE,A,B,C,D,E)"

.PP
Definition at line 166 of file ncfortran\&.h\&.
.SS "#define PTYPE_cfT(M, I, A, B, D)   &B"

.PP
Definition at line 169 of file ncfortran\&.h\&.
.SS "#define PTYPE_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 165 of file ncfortran\&.h\&.
.SS "#define PVARID   PCNDX2FNDX"

.PP
Definition at line 582 of file ncfortran\&.h\&.
.SS "#define REALATT   \fBREALVARV\fP"

.PP
Definition at line 127 of file ncfortran\&.h\&.
.SS "#define REALVAR_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 379 of file ncfortran\&.h\&.
.SS "#define REALVAR_cfN(T, A)   const float *A"

.PP
Definition at line 384 of file ncfortran\&.h\&.
.SS "#define REALVAR_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 380 of file ncfortran\&.h\&.
.SS "#define REALVAR_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 386 of file ncfortran\&.h\&.
.SS "#define REALVAR_cfT(M, I, A, B, D)   A"

.PP
Definition at line 387 of file ncfortran\&.h\&.
.SS "#define REALVARV   REALVAR"

.PP
Definition at line 407 of file ncfortran\&.h\&.
.SS "#define STRIDES_cfH(S, U, B)"

.PP
Definition at line 639 of file ncfortran\&.h\&.
.SS "#define STRIDES_cfINT(N, A, B, X, Y, Z)   \fBDOUBLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 636 of file ncfortran\&.h\&.
.SS "#define STRIDES_cfQ(B)   ptrdiff_t B[NC_MAX_DIMS];"

.PP
Definition at line 640 of file ncfortran\&.h\&.
.SS "#define STRIDES_cfR(A, B, D)"

.PP
Definition at line 642 of file ncfortran\&.h\&.
.SS "#define STRIDES_cfSTR(N, T, A, B, C, D, E)   \fB_\fP(CFARGS,N)(T,STRIDES,A,B,C,D,E)"

.PP
Definition at line 638 of file ncfortran\&.h\&.
.SS "#define STRIDES_cfT(M, I, A, B, D)   \fBf2c_strides\fP(*fncid, *fvarid\-1, A, B)"

.PP
Definition at line 641 of file ncfortran\&.h\&.
.SS "#define STRIDESVVVVVVV_cfTYPE   \fBNF_INTEGER\fP"

.PP
Definition at line 637 of file ncfortran\&.h\&.
.SS "#define TEXTATT   STRING"

.PP
Definition at line 115 of file ncfortran\&.h\&.
.SS "#define TEXTVAR   STRING"

.PP
Definition at line 231 of file ncfortran\&.h\&.
.SS "#define TEXTVARV   STRING"

.PP
Definition at line 243 of file ncfortran\&.h\&.
.SS "#define TYPE_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 154 of file ncfortran\&.h\&.
.SS "#define TYPE_cfN(T, A)   \fBNF_INTEGER\fP *A"

.PP
Definition at line 156 of file ncfortran\&.h\&.
.SS "#define TYPE_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 155 of file ncfortran\&.h\&.
.SS "#define TYPE_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 157 of file ncfortran\&.h\&.
.SS "#define TYPE_cfT(M, I, A, B, D)   ((nc_type)*A)"

.PP
Definition at line 158 of file ncfortran\&.h\&.
.SS "#define VARID1_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 566 of file ncfortran\&.h\&.
.SS "#define VARID1_cfN(T, A)   \fBNF_INTEGER\fP *fvarid1"

.PP
Definition at line 568 of file ncfortran\&.h\&.
.SS "#define VARID1_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 567 of file ncfortran\&.h\&.
.SS "#define VARID1_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 569 of file ncfortran\&.h\&.
.SS "#define VARID1_cfT(M, I, A, B, D)   (*fvarid1\-1)"

.PP
Definition at line 570 of file ncfortran\&.h\&.
.SS "#define VARID2_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 572 of file ncfortran\&.h\&.
.SS "#define VARID2_cfN(T, A)   \fBNF_INTEGER\fP *fvarid2"

.PP
Definition at line 574 of file ncfortran\&.h\&.
.SS "#define VARID2_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 573 of file ncfortran\&.h\&.
.SS "#define VARID2_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 575 of file ncfortran\&.h\&.
.SS "#define VARID2_cfT(M, I, A, B, D)   (*fvarid2\-1)"

.PP
Definition at line 576 of file ncfortran\&.h\&.
.SS "#define VARID_cfINT(N, A, B, X, Y, Z)   \fBSIMPLE_cfINT\fP(N,A,B,X,Y,Z)"

.PP
Definition at line 556 of file ncfortran\&.h\&.
.SS "#define VARID_cfN(T, A)   \fBNF_INTEGER\fP *fvarid"

.PP
Definition at line 558 of file ncfortran\&.h\&.
.SS "#define VARID_cfSEP(T, B)   \fBSIMPLE_cfSEP\fP(T,B)"

.PP
Definition at line 557 of file ncfortran\&.h\&.
.SS "#define VARID_cfSTR(N, T, A, B, C, D, E)   \fBSIMPLE_cfSTR\fP(N,T,A,B,C,D,E)"

.PP
Definition at line 559 of file ncfortran\&.h\&.
.SS "#define VARID_cfT(M, I, A, B, D)   (*fvarid\-1)"

.PP
Definition at line 560 of file ncfortran\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
