.TH "netcdf_nf_interfaces::nf_get_att_double" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_get_att_double
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_get_att_double\fP (ncid, varid, name, dvals)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1642 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_get_att_double::nf_get_att_double (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, real(rk8), dimension(*), intent(out) dvals)"

.PP
Definition at line 1643 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
