.TH "netcdf_nc_interfaces::nc_inq_dimlen" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_inq_dimlen
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_dimlen\fP (ncid, dimid, lenp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 485 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_inq_dimlen::nc_inq_dimlen (integer(c_int), value ncid, integer(c_int), value dimid, integer(c_size_t), intent(out) lenp)"

.PP
Definition at line 486 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
