.TH "netcdf_fortv2_c_interfaces::c_ncsfil" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncsfil
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBc_ncsfil\fP (ncid, fillmode, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 570 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_fortv2_c_interfaces::c_ncsfil::c_ncsfil (integer(c_int), value ncid, integer(c_int), value fillmode, integer(c_int), intent(out) rcode)"

.PP
Definition at line 571 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
