.TH "netcdf_nf_interfaces::nf_get_vara_text" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_get_vara_text
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_get_vara_text\fP (ncid, varid, start, counts, text)"
.br
.ti -1c
.RI "integer function \fBnf_get_vara_text_a\fP (ncid, varid, start, counts, text)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1394 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_get_vara_text::nf_get_vara_text (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, character(len=*), intent(out) text)"

.PP
Definition at line 1396 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_get_vara_text::nf_get_vara_text_a (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, character(len=1), dimension(*), intent(out) text)"

.PP
Definition at line 1405 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
