.TH "netcdf_fortv2_c_interfaces" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBc_ncabor\fP"
.br
.ti -1c
.RI "interface \fBc_ncacpy\fP"
.br
.ti -1c
.RI "interface \fBc_ncadel\fP"
.br
.ti -1c
.RI "interface \fBc_ncagt\fP"
.br
.ti -1c
.RI "interface \fBc_ncagtc\fP"
.br
.ti -1c
.RI "interface \fBc_ncainq\fP"
.br
.ti -1c
.RI "interface \fBc_ncanam\fP"
.br
.ti -1c
.RI "interface \fBc_ncapt\fP"
.br
.ti -1c
.RI "interface \fBc_ncaptc\fP"
.br
.ti -1c
.RI "interface \fBc_ncaren\fP"
.br
.ti -1c
.RI "interface \fBc_ncclos\fP"
.br
.ti -1c
.RI "interface \fBc_nccre\fP"
.br
.ti -1c
.RI "interface \fBc_ncddef\fP"
.br
.ti -1c
.RI "interface \fBc_ncdid\fP"
.br
.ti -1c
.RI "interface \fBc_ncdinq\fP"
.br
.ti -1c
.RI "interface \fBc_ncdren\fP"
.br
.ti -1c
.RI "interface \fBc_ncendf\fP"
.br
.ti -1c
.RI "interface \fBc_ncgopt\fP"
.br
.ti -1c
.RI "interface \fBc_ncinq\fP"
.br
.ti -1c
.RI "interface \fBc_ncopn\fP"
.br
.ti -1c
.RI "interface \fBc_ncpopt\fP"
.br
.ti -1c
.RI "interface \fBc_ncredf\fP"
.br
.ti -1c
.RI "interface \fBc_ncsfil\fP"
.br
.ti -1c
.RI "interface \fBc_ncsnc\fP"
.br
.ti -1c
.RI "interface \fBc_nctlen\fP"
.br
.ti -1c
.RI "interface \fBc_ncvdef\fP"
.br
.ti -1c
.RI "interface \fBc_ncvg1c\fP"
.br
.ti -1c
.RI "interface \fBc_ncvggc\fP"
.br
.ti -1c
.RI "interface \fBc_ncvgt\fP"
.br
.ti -1c
.RI "interface \fBc_ncvgt1\fP"
.br
.ti -1c
.RI "interface \fBc_ncvgtc\fP"
.br
.ti -1c
.RI "interface \fBc_ncvgtg\fP"
.br
.ti -1c
.RI "interface \fBc_ncvid\fP"
.br
.ti -1c
.RI "interface \fBc_ncvinq\fP"
.br
.ti -1c
.RI "interface \fBc_ncvp1c\fP"
.br
.ti -1c
.RI "interface \fBc_ncvpgc\fP"
.br
.ti -1c
.RI "interface \fBc_ncvpt\fP"
.br
.ti -1c
.RI "interface \fBc_ncvpt1\fP"
.br
.ti -1c
.RI "interface \fBc_ncvptc\fP"
.br
.ti -1c
.RI "interface \fBc_ncvptg\fP"
.br
.ti -1c
.RI "interface \fBc_ncvren\fP"
.br
.ti -1c
.RI "interface \fBv2data_size\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBconvert_v2_imap\fP (cncid, cvarid, fmap, cmap, inullp)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::convert_v2_imap (integer(c_int), intent(in) cncid, integer(c_int), intent(in) cvarid, integer(c_int), dimension(*), intent(in) fmap, integer(c_ptrdiff_t), dimension(:), intent(inout) cmap, integer, intent(out) inullp)"

.PP
Definition at line 598 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
