.TH "netcdf_fortv2_c_interfaces::c_ncaren" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncaren
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBc_ncaren\fP (ncid, varid, attnam, newname, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 546 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::c_ncaren::c_ncaren (integer(c_int), value ncid, integer(c_int), value varid, character(kind=c_char), dimension(*), intent(in) attnam, character(kind=c_char), dimension(*), intent(in) newname, integer(c_int), intent(out) rcode)"

.PP
Definition at line 547 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
