.TH "netcdf_fortv2_c_interfaces::v2data_size" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::v2data_size
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_size_t) function \fBv2data_size\fP (datatype)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 583 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_size_t) function netcdf_fortv2_c_interfaces::v2data_size::v2data_size (integer(c_int), value datatype)"

.PP
Definition at line 584 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
