.TH "netcdf_nf_interfaces::nf__enddef" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf__enddef
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf__enddef\fP (ncid, h_minfree, v_align, v_minfree, r_align)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 216 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf_nf_interfaces::nf__enddef::nf__enddef (intent(in) ncid, intent(in) h_minfree, intent(in) v_align, intent(in) v_minfree, intent(in) r_align)"

.PP
Definition at line 220 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
