.TH "netcdf4_nf_interfaces::nf_def_opaque" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_def_opaque
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_def_opaque\fP (ncid, isize, name, xtype)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 492 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_def_opaque::nf_def_opaque (integer, intent(in) ncid, integer, intent(in) isize, character(len=*), intent(in) name, integer, intent(out) xtype)"

.PP
Definition at line 493 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
