.TH "netcdf4_nf_interfaces::nf_inq_grpname" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_grpname
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_grpname\fP (ncid, name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_grpname::nf_inq_grpname (integer, intent(in) ncid, character(len=*), intent(out) name)"

.PP
Definition at line 93 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
