.TH "netcdf_nf_interfaces::nf_get_vars_double" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_get_vars_double
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_get_vars_double\fP (ncid, varid, start, counts, strides, dvals)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1102 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf_nf_interfaces::nf_get_vars_double::nf_get_vars_double (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, real(rk8), dimension(*), intent(out) dvals)"

.PP
Definition at line 1106 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
