.TH "netcdf_nc_interfaces::stripcnullchar" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::stripcnullchar
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "character(len=nlen) function \fBstripcnullchar\fP (cstring, nlen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "character(len=nlen) function netcdf_nc_interfaces::stripcnullchar::stripcnullchar (character(len=*), intent(in) cstring, integer, intent(in) nlen)"

.PP
Definition at line 2313 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
