.TH "netcdf_nc_interfaces::nc_inq_attlen" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_inq_attlen
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_attlen\fP (ncid, varid, name, lenp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1929 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_inq_attlen::nc_inq_attlen (integer(c_int), value ncid, integer(c_int), value varid, character(kind=c_char), dimension(*), intent(in) name, integer(c_size_t), intent(out) lenp)"

.PP
Definition at line 1930 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
