.TH "netcdf4_nf_interfaces::nf_insert_compound" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_insert_compound
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_insert_compound\fP (ncid, xtype, name, offset, field_typeid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 237 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf4_nf_interfaces::nf_insert_compound::nf_insert_compound (intent(in) ncid, intent(in) xtype, character(len=*), intent(in) name, intent(in) offset, intent(in) field_typeid)"

.PP
Definition at line 241 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
