.TH "netcdf_nf_interfaces::nf_inq_dimname" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_inq_dimname
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_dimname\fP (ncid, dimid, name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 338 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_inq_dimname::nf_inq_dimname (integer, intent(in) ncid, integer, intent(in) dimid, character(len=*), intent(out) name)"

.PP
Definition at line 339 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
