.TH "netcdf_variables.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_variables.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnf90_def_var_scalar\fP (ncid, name, xtype, varid)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_onedim\fP (ncid, name, xtype, dimids, varid)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_manydims\fP (ncid, name, xtype, dimids, varid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_varid\fP (ncid, name, varid)"
.br
.ti -1c
.RI "integer function \fBnf90_inquire_variable\fP (ncid, varid, name, xtype, ndims, dimids, nAtts)"
.br
.ti -1c
.RI "integer function \fBnf90_rename_var\fP (ncid, varid, newname)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function nf90_def_var_manydims (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(in) xtype, integer, dimension(:), intent(in) dimids, integer, intent(out) varid)"

.PP
Definition at line 31 of file netcdf_variables\&.f90\&.
.SS "integer function nf90_def_var_onedim (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(in) xtype, integer, intent(in) dimids, integer, intent(out) varid)"

.PP
Definition at line 18 of file netcdf_variables\&.f90\&.
.SS "integer function nf90_def_var_scalar (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(in) xtype, integer, intent(out) varid)"

.PP
Definition at line 5 of file netcdf_variables\&.f90\&.
.SS "integer function nf90_inq_varid (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(out) varid)"

.PP
Definition at line 42 of file netcdf_variables\&.f90\&.
.SS "integer function nf90_inquire_variable (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), intent(out), optional name, integer, intent(out), optional xtype, integer, intent(out), optional ndims, integer, dimension(:), intent(out), optional dimids, integer, intent(out), optional nAtts)"

.PP
Definition at line 51 of file netcdf_variables\&.f90\&.
.SS "integer function nf90_rename_var (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), intent(in) newname)"

.PP
Definition at line 82 of file netcdf_variables\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
