.TH "netcdf_nf_interfaces::nf_def_var" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_def_var
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_def_var\fP (ncid, name, xtype, nvdims, vdims, varid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 424 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_def_var::nf_def_var (integer, intent(in) ncid, character(len=*), intent(in) name, integer, intent(in) xtype, integer, intent(in) nvdims, integer, dimension(*), intent(in) vdims, integer, intent(out) varid)"

.PP
Definition at line 425 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
