.TH "netcdf_nc_interfaces::nc_copy_var" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_copy_var
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_copy_var\fP (ncid_in, varid, ncid_out)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2241 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_copy_var::nc_copy_var (integer(c_int), value ncid_in, integer(c_int), value varid, integer(c_int), value ncid_out)"

.PP
Definition at line 2242 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
