.TH "netcdf_nf_interfaces::nf_inq_varnatts" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_inq_varnatts
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_varnatts\fP (ncid, varid, nvatts)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 500 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_inq_varnatts::nf_inq_varnatts (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(out) nvatts)"

.PP
Definition at line 501 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
