.TH "netcdf_nc_interfaces::nc_get_vars_schar" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_get_vars_schar
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_get_vars_schar\fP (ncid, varid, startp, countp, stridep, ip)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1450 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_get_vars_schar::nc_get_vars_schar (integer(c_int), value ncid, integer(c_int), value varid, type(c_ptr), value startp, type(c_ptr), value countp, type(c_ptr), value stridep, integer(cint1), dimension(*), intent(out) ip)"

.PP
Definition at line 1451 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
