.TH "netcdf4_nc_interfaces::nc_inq_user_type" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_inq_user_type
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_user_type\fP (ncid, xtype, name, isize, base_nc_typep, nfieldsp, classp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 590 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_inq_user_type::nc_inq_user_type (integer(c_int), value ncid, integer(c_int), value xtype, character(kind=c_char), dimension(*), intent(inout) name, integer(c_size_t), intent(inout) isize, integer(c_int), intent(inout) base_nc_typep, integer(c_size_t), intent(inout) nfieldsp, integer(c_int), intent(inout) classp)"

.PP
Definition at line 592 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
