.TH "netcdf_nf_interfaces::nf__create" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf__create
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf__create\fP (path, cmode, initialsz, chunksizehintp, ncid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf_nf_interfaces::nf__create::nf__create (intent(in) path, integer, intent(in) cmode, integer, intent(in) initialsz, integer, intent(in) chunksizehintp, integer, intent(out) ncid)"

.PP
Definition at line 98 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
