.TH "netcdf4_nf_interfaces::nf_def_vlen" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_def_vlen
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_def_vlen\fP (ncid, name, base_typeid, xtype)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 391 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_def_vlen::nf_def_vlen (integer, intent(in) ncid, character(len=*), intent(in) name, integer, intent(in) base_typeid, integer, intent(out) xtype)"

.PP
Definition at line 392 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
