.TH "netcdf_fortv2_c_interfaces::c_ncinq" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncinq
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBc_ncinq\fP (ncid, indims, invars, inatts, irecdim, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 205 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::c_ncinq::c_ncinq (integer(c_int), value ncid, integer(c_int), intent(out) indims, integer(c_int), intent(out) invars, integer(c_int), intent(out) inatts, integer(c_int), intent(out) irecdim, integer(c_int), intent(out) rcode)"

.PP
Definition at line 206 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
