.TH "netcdf_fortv2_c_interfaces::c_ncacpy" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncacpy
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBc_ncacpy\fP (inncid, invarid, attname, outncid, outvarid, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 521 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::c_ncacpy::c_ncacpy (integer(c_int), value inncid, integer(c_int), value invarid, character(kind=c_char), dimension(*), intent(in) attname, integer(c_int), value outncid, integer(c_int), value outvarid, integer(c_int), intent(out) rcode)"

.PP
Definition at line 523 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
