.TH "netcdf4_nf_interfaces::nf_inq_var_szip" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_var_szip
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_var_szip\fP (ncid, varid, options_mask, pixels_per_block)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 558 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_var_szip::nf_inq_var_szip (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(inout) options_mask, integer, intent(inout) pixels_per_block)"

.PP
Definition at line 559 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
