.TH "netcdf_nc_interfaces::nc__enddef" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc__enddef
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc__enddef\fP (ncid, h_minfree, v_align, v_minfree, r_align)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 250 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc__enddef::nc__enddef (integer(c_int), value ncid, integer(c_size_t), value h_minfree, integer(c_size_t), value v_align, integer(c_size_t), value v_minfree, integer(c_size_t), value r_align)"

.PP
Definition at line 251 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
