.TH "netcdf_dims.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_dims.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnf90_def_dim\fP (ncid, name, len, dimid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_dimid\fP (ncid, name, dimid)"
.br
.ti -1c
.RI "integer function \fBnf90_rename_dim\fP (ncid, dimid, name)"
.br
.ti -1c
.RI "integer function \fBnf90_inquire_dimension\fP (ncid, dimid, name, len)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function nf90_def_dim (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(in) len, integer, intent(out) dimid)"

.PP
Definition at line 6 of file netcdf_dims\&.f90\&.
.SS "integer function nf90_inq_dimid (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(out) dimid)"

.PP
Definition at line 16 of file netcdf_dims\&.f90\&.
.SS "integer function nf90_inquire_dimension (integer, intent(in) ncid, integer, intent(in) dimid, character (len = *), intent(out), optional name, integer, intent(out), optional len)"

.PP
Definition at line 34 of file netcdf_dims\&.f90\&.
.SS "integer function nf90_rename_dim (integer, intent(in) ncid, integer, intent(in) dimid, character (len = *), intent(in) name)"

.PP
Definition at line 25 of file netcdf_dims\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
