.TH "netcdf_nc_interfaces::nc_copy_att" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_copy_att
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_copy_att\fP (ncid_in, varid_in, name, ncid_out, varid_out)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1956 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_copy_att::nc_copy_att (integer(c_int), value ncid_in, integer(c_int), value varid_in, character(kind=c_char), dimension(*), intent(in) name, integer(c_int), value ncid_out, integer(c_int), value varid_out)"

.PP
Definition at line 1957 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
