.TH "netcdf4_nf_interfaces::nf_create_par" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_create_par
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_create_par\fP (path, cmode, comm, info, ncid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_create_par::nf_create_par (character(len=*), intent(in) path, integer, intent(in) cmode, integer, intent(in) comm, integer, intent(in) info, integer, intent(out) ncid)"

.PP
Definition at line 40 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
