.TH "netcdf_nf_interfaces::nf_put_var_int" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_put_var_int
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_put_var_int\fP (ncid, varid, ivals)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 815 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_put_var_int::nf_put_var_int (integer, intent(in) ncid, integer, intent(in) varid, integer(nfint), dimension(*), intent(in) ivals)"

.PP
Definition at line 816 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
