.TH "netcdf_nc_interfaces::nc_inq_vartype" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_inq_vartype
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_vartype\fP (ncid, varid, xtypep)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 575 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_inq_vartype::nc_inq_vartype (integer(c_int), value ncid, integer(c_int), value varid, integer(c_int), intent(out) xtypep)"

.PP
Definition at line 576 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
