.TH "netcdf_nf_interfaces::nf90_open_mem" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf90_open_mem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_open_mem\fP (path, mode, size, memory, ncid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 150 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf90_open_mem::nf_open_mem (character(len=*), intent(in) path, integer, intent(in) mode, integer, intent(in) size, character(kind=c_char), dimension(*), intent(in), target memory, integer, intent(inout) ncid)"

.PP
Definition at line 152 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
