.TH "netcdf_fortv2_c_interfaces::c_ncvptc" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncvptc
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBc_ncvptc\fP (ncid, varid, start, count, value, lenstr, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 316 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::c_ncvptc::c_ncvptc (integer(c_int), value ncid, integer(c_int), value varid, type(c_ptr), value start, type(c_ptr), value count, character(kind=c_char), dimension(*), intent(in) value, integer(c_int), value lenstr, integer(c_int), intent(out) rcode)"

.PP
Definition at line 317 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
