.TH "netcdf_nc_interfaces::nc_get_var_short" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_get_var_short
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_get_var_short\fP (ncid, varid, ip)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 736 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_get_var_short::nc_get_var_short (integer(c_int), value ncid, integer(c_int), value varid, integer(cint2), dimension(*), intent(out) ip)"

.PP
Definition at line 737 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
