.TH "netcdf4_nc_interfaces::nc_inq_enum_member" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_inq_enum_member
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_enum_member\fP (ncid, xtype, idx, name, value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 655 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_inq_enum_member::nc_inq_enum_member (integer(c_int), value ncid, integer(c_int), value xtype, integer(c_int), value idx, character(kind=c_char), dimension(*), intent(inout) name, character(kind=c_char), dimension(*), intent(out) value)"

.PP
Definition at line 656 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
