.TH "netcdf4_nf_interfaces::nf_inq_compound_fieldtype" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_compound_fieldtype
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_inq_compound_fieldtype\fP (ncid, xtype, fieldid, field_typeid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 358 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf4_nf_interfaces::nf_inq_compound_fieldtype::nf_inq_compound_fieldtype (intent(in) ncid, intent(in) xtype, intent(in) fieldid, integer, intent(out) field_typeid)"

.PP
Definition at line 362 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
