.TH "netcdf_nc_interfaces::nc_inq_atttype" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_inq_atttype
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_atttype\fP (ncid, varid, name, xtypep)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1915 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_inq_atttype::nc_inq_atttype (integer(c_int), value ncid, integer(c_int), value varid, character(kind=c_char), dimension(*), intent(in) name, integer(c_int), intent(out) xtypep)"

.PP
Definition at line 1916 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
