.TH "netcdf4_nc_interfaces::nc_inq_var_chunking" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_inq_var_chunking
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_var_chunking\fP (ncid, varid, contiguousp, chunksizesp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 818 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_inq_var_chunking::nc_inq_var_chunking (integer(c_int), value ncid, integer(c_int), value varid, integer(c_int), intent(inout) contiguousp, integer(c_size_t), dimension(*), intent(inout) chunksizesp)"

.PP
Definition at line 819 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
