.TH "netcdf_nf_interfaces::nf_inq_libvers" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_inq_libvers
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "character(len=80) function \fBnf_inq_libvers\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "character(len=80) function netcdf_nf_interfaces::nf_inq_libvers::nf_inq_libvers ()"

.PP
Definition at line 55 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
