.TH "netcdf4_nf_interfaces::nf_inq_vlen" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_vlen
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_vlen\fP (ncid, xtype, name, datum_size, base_type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 402 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_vlen::nf_inq_vlen (integer, intent(in) ncid, integer, intent(in) xtype, character(len=*), intent(out) name, integer, intent(out) datum_size, integer, intent(out) base_type)"

.PP
Definition at line 403 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
