.TH "netcdf4_nf_interfaces::nf_inq_var_chunking" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_var_chunking
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_inq_var_chunking\fP (ncid, varid, contiguous, chunksizes)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 525 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf4_nf_interfaces::nf_inq_var_chunking::nf_inq_var_chunking (intent(in) ncid, intent(in) varid, integer, intent(inout) contiguous, integer, dimension(*), intent(inout) chunksizes)"

.PP
Definition at line 529 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
