.TH "netcdf4_nf_interfaces" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBnf_create_par\fP"
.br
.ti -1c
.RI "interface \fBnf_def_compound\fP"
.br
.ti -1c
.RI "interface \fBnf_def_enum\fP"
.br
.ti -1c
.RI "interface \fBnf_def_grp\fP"
.br
.ti -1c
.RI "interface \fBnf_def_opaque\fP"
.br
.ti -1c
.RI "interface \fBnf_def_var_chunking\fP"
.br
.ti -1c
.RI "interface \fBnf_def_var_deflate\fP"
.br
.ti -1c
.RI "interface \fBnf_def_var_endian\fP"
.br
.ti -1c
.RI "interface \fBnf_def_var_fletcher32\fP"
.br
.ti -1c
.RI "interface \fBnf_def_vlen\fP"
.br
.ti -1c
.RI "interface \fBnf_get_chunk_cache\fP"
.br
.ti -1c
.RI "interface \fBnf_get_var1_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_get_var_chunk_cache\fP"
.br
.ti -1c
.RI "interface \fBnf_get_var_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_get_vara_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_get_varm_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_get_vars_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_field\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_fielddim_sizes\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_fieldindex\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_fieldname\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_fieldndims\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_fieldoffset\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_fieldtype\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_name\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_nfields\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_compound_size\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_dimids\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_enum\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_enum_ident\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_grp_full_ncid\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_grp_ncid\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_grp_parent\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_grpname\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_grpname_full\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_grpname_len\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_grps\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_ncid\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_opaque\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_type\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_typeid\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_typeids\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_user_type\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_var_chunking\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_var_deflate\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_var_endian\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_var_fletcher32\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_var_szip\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_varids\fP"
.br
.ti -1c
.RI "interface \fBnf_inq_vlen\fP"
.br
.ti -1c
.RI "interface \fBnf_insert_array_compound\fP"
.br
.ti -1c
.RI "interface \fBnf_insert_compound\fP"
.br
.ti -1c
.RI "interface \fBnf_open_par\fP"
.br
.ti -1c
.RI "interface \fBnf_put_var1_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_put_var_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_put_vara_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_put_varm_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_put_vars_int64\fP"
.br
.ti -1c
.RI "interface \fBnf_rename_grp\fP"
.br
.ti -1c
.RI "interface \fBnf_set_chunk_cache\fP"
.br
.ti -1c
.RI "interface \fBnf_set_var_chunk_cache\fP"
.br
.ti -1c
.RI "interface \fBnf_var_par_access\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, external \fBnf_insert_enum\fP"
.br
.ti -1c
.RI "integer, external \fBnf_inq_enum_member\fP"
.br
.ti -1c
.RI "integer, external \fBnf_put_att\fP"
.br
.ti -1c
.RI "integer, external \fBnf_get_att\fP"
.br
.ti -1c
.RI "integer, external \fBnf_put_vlen_element\fP"
.br
.ti -1c
.RI "integer, external \fBnf_get_vlen_element\fP"
.br
.ti -1c
.RI "integer, external \fBnf_free_vlen\fP"
.br
.ti -1c
.RI "integer, external \fBnf_free_vlens\fP"
.br
.ti -1c
.RI "integer, external \fBnf_free_string\fP"
.br
.ti -1c
.RI "integer, external \fBnf_put_var\fP"
.br
.ti -1c
.RI "integer, external \fBnf_get_var\fP"
.br
.ti -1c
.RI "integer, external \fBnf_def_var_fill\fP"
.br
.ti -1c
.RI "integer, external \fBnf_inq_var_fill\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "integer, external netcdf4_nf_interfaces::nf_def_var_fill"

.PP
Definition at line 927 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_free_string"

.PP
Definition at line 924 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_free_vlen"

.PP
Definition at line 922 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_free_vlens"

.PP
Definition at line 923 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_get_att"

.PP
Definition at line 919 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_get_var"

.PP
Definition at line 926 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_get_vlen_element"

.PP
Definition at line 921 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_inq_enum_member"

.PP
Definition at line 917 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_inq_var_fill"

.PP
Definition at line 928 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_insert_enum"

.PP
Definition at line 916 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_put_att"

.PP
Definition at line 918 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_put_var"

.PP
Definition at line 925 of file module_netcdf4_nf_interfaces\&.F90\&.
.SS "integer, external netcdf4_nf_interfaces::nf_put_vlen_element"

.PP
Definition at line 920 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
