.TH "netcdf_attributes.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_attributes.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnf90_copy_att\fP (ncid_in, varid_in, name, ncid_out, varid_out)"
.br
.ti -1c
.RI "integer function \fBnf90_rename_att\fP (ncid, varid, curname, newname)"
.br
.ti -1c
.RI "integer function \fBnf90_del_att\fP (ncid, varid, name)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_attname\fP (ncid, varid, attnum, name)"
.br
.ti -1c
.RI "integer function \fBnf90_inquire_attribute\fP (ncid, varid, name, xtype, len, attnum)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_text\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_text\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_onebyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_one_onebyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_onebyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_one_onebyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_twobyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_one_twobyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_twobyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_one_twobyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_fourbyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_one_fourbyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_fourbyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_one_fourbyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_eightbyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_one_eightbyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_eightbyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_one_eightbyteint\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_fourbytereal\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_one_fourbytereal\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_fourbytereal\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_one_fourbytereal\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_eightbytereal\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_one_eightbytereal\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_eightbytereal\fP (ncid, varid, name, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_one_eightbytereal\fP (ncid, varid, name, values)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function nf90_copy_att (integer, intent(in) ncid_in, integer, intent(in) varid_in, character (len = *), intent(in) name, integer, intent(in) ncid_out, integer, intent(in) varid_out)"

.PP
Definition at line 6 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_del_att (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), intent(in) name)"

.PP
Definition at line 23 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_eightbyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = eightbyteint), dimension(:), intent(out) values)"

.PP
Definition at line 226 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_eightbytereal (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, real (kind = eightbytereal), dimension(:), intent(out) values)"

.PP
Definition at line 312 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_fourbyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = fourbyteint), dimension(:), intent(out) values)"

.PP
Definition at line 182 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_fourbytereal (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, real (kind = fourbytereal), dimension(:), intent(out) values)"

.PP
Definition at line 272 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_one_eightbyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = eightbyteint), intent(out) values)"

.PP
Definition at line 238 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_one_eightbytereal (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, real (kind = eightbytereal), intent(out) values)"

.PP
Definition at line 321 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_one_fourbyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = fourbyteint), intent(out) values)"

.PP
Definition at line 194 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_one_fourbytereal (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, real (kind = fourbytereal), intent(out) values)"

.PP
Definition at line 281 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_one_onebyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = onebyteint), intent(out) values)"

.PP
Definition at line 111 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_one_twobyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = twobyteint), intent(out) values)"

.PP
Definition at line 151 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_onebyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = onebyteint), dimension(:), intent(out) values)"

.PP
Definition at line 102 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_text (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, character(len = *), intent(out) values)"

.PP
Definition at line 70 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_get_att_twobyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = twobyteint), dimension(:), intent(out) values)"

.PP
Definition at line 142 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_inq_attname (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) attnum, character (len = *), intent(out) name)"

.PP
Definition at line 33 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_inquire_attribute (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), intent(in) name, integer, intent(out), optional xtype, integer, intent(out), optional len, integer, intent(out), optional attnum)"

.PP
Definition at line 41 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_eightbyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = eightbyteint), dimension(:), intent(in) values)"

.PP
Definition at line 206 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_eightbytereal (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, real (kind = eightbytereal), dimension(:), intent(in) values)"

.PP
Definition at line 292 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_fourbyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = fourbyteint), dimension(:), intent(in) values)"

.PP
Definition at line 162 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_fourbytereal (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, real (kind = fourbytereal), dimension(:), intent(in) values)"

.PP
Definition at line 252 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_one_eightbyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = eightbyteint), intent(in) values)"

.PP
Definition at line 215 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_one_eightbytereal (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, real (kind = eightbytereal), intent(in) values)"

.PP
Definition at line 301 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_one_fourbyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = fourbyteint), intent(in) values)"

.PP
Definition at line 171 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_one_fourbytereal (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, real (kind = fourbytereal), intent(in) values)"

.PP
Definition at line 261 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_one_onebyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = onebyteint), intent(in) values)"

.PP
Definition at line 91 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_one_twobyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = twobyteint), intent(in) values)"

.PP
Definition at line 131 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_onebyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = onebyteint), dimension(:), intent(in) values)"

.PP
Definition at line 82 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_text (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, character(len = *), intent(in) values)"

.PP
Definition at line 61 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_put_att_twobyteint (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer (kind = twobyteint), dimension(:), intent(in) values)"

.PP
Definition at line 122 of file netcdf_attributes\&.f90\&.
.SS "integer function nf90_rename_att (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), intent(in) curname, character (len = *), intent(in) newname)"

.PP
Definition at line 15 of file netcdf_attributes\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
