.TH "netcdf_fortv2_c_interfaces::c_ncvdef" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncvdef
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBc_ncvdef\fP (ncid, varname, datatype, ndims, dimidp, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_fortv2_c_interfaces::c_ncvdef::c_ncvdef (integer(c_int), value ncid, character(kind=c_char), dimension(*), intent(in) varname, integer(c_int), value datatype, integer(c_int), value ndims, type(c_ptr), value dimidp, integer(c_int), intent(out) rcode)"

.PP
Definition at line 129 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
