.TH "netcdf_nf_interfaces::nf_inq_att" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_inq_att
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_att\fP (ncid, varid, name, xtype, nlen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 532 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_inq_att::nf_inq_att (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(out) xtype, integer, intent(out) nlen)"

.PP
Definition at line 533 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
