.TH "netcdf_nc_interfaces::nc_get_varm_text" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_get_varm_text
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_get_varm_text\fP (ncid, varid, startp, countp, stridep, imapp, ip)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1653 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_get_varm_text::nc_get_varm_text (integer(c_int), value ncid, integer(c_int), value varid, type(c_ptr), value startp, type(c_ptr), value countp, type(c_ptr), value stridep, type(c_ptr), value imapp, character(kind=c_char), dimension(*), intent(out) ip)"

.PP
Definition at line 1655 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
