.TH "netcdf_nf_interfaces::nf_get_vars_int1" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_get_vars_int1
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_get_vars_int1\fP (ncid, varid, start, counts, strides, i1vals)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1046 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf_nf_interfaces::nf_get_vars_int1::nf_get_vars_int1 (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, integer(nfint1), dimension(*), intent(out) i1vals)"

.PP
Definition at line 1050 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
