.TH "netcdf_nf_interfaces::nf_put_var1_int2" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_put_var1_int2
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_put_var1_int2\fP (ncid, varid, ndex, ival)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 644 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_put_var1_int2::nf_put_var1_int2 (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) ndex, integer(nfint2), intent(in) ival)"

.PP
Definition at line 645 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
