.TH "netcdf_nf_interfaces::nf_create" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_create
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_create\fP (path, cmode, ncid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_create::nf_create (character(len=*), intent(in) path, integer, intent(in) cmode, integer, intent(out) ncid)"

.PP
Definition at line 84 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
