.TH "netcdf4_nf_interfaces::nf_def_var_deflate" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_def_var_deflate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_def_var_deflate\fP (ncid, varid, shuffle, deflate, deflate_level)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 537 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf4_nf_interfaces::nf_def_var_deflate::nf_def_var_deflate (intent(in) ncid, intent(in) varid, intent(in) shuffle, intent(in) deflate, intent(in) deflate_level)"

.PP
Definition at line 541 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
