.TH "netcdf4_nc_interfaces::nc_inq_compound_fielddim_sizes" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_inq_compound_fielddim_sizes
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_compound_fielddim_sizes\fP (ncid, xtype, fieldid, dim_sizes)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 545 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_inq_compound_fielddim_sizes::nc_inq_compound_fielddim_sizes (integer(c_int), value ncid, integer(c_int), value xtype, integer(c_int), value fieldid, integer(c_int), dimension(*), intent(inout) dim_sizes)"

.PP
Definition at line 546 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
