.TH "netcdf4_nc_interfaces::nc_inq_var_szip" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_inq_var_szip
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_var_szip\fP (ncid, varid, options_mask, pixels_per_block)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 742 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_inq_var_szip::nc_inq_var_szip (integer(c_int), value ncid, integer(c_int), value varid, integer(c_int), intent(inout) options_mask, integer(c_int), intent(inout) pixels_per_block)"

.PP
Definition at line 743 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
