.TH "netcdf4_nc_interfaces::nc_def_compound" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_def_compound
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_def_compound\fP (ncid, isize, name, typeidp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 318 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_def_compound::nc_def_compound (integer(c_int), value ncid, integer(c_size_t), value isize, character(kind=c_char), dimension(*), intent(in) name, integer(c_int), intent(inout) typeidp)"

.PP
Definition at line 319 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
