.TH "netcdf4_nc_interfaces::nc_inq_var_endian" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_inq_var_endian
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_var_endian\fP (ncid, varid, endiann)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 871 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_inq_var_endian::nc_inq_var_endian (integer(c_int), value ncid, integer(c_int), value varid, integer(c_int), intent(inout) endiann)"

.PP
Definition at line 872 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
