.TH "netcdf_fortv2_c_interfaces::c_ncvpt1" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncvpt1
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBc_ncvpt1\fP (ncid, varid, indices, value, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 277 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::c_ncvpt1::c_ncvpt1 (integer(c_int), value ncid, integer(c_int), value varid, type(c_ptr), value indices, type(c_ptr), value value, integer(c_int), intent(out) rcode)"

.PP
Definition at line 278 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
