.TH "netcdf4_nc_interfaces::nc_get_vlen_element" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_get_vlen_element
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_get_vlen_element\fP (ncid, xtype, vlen_element, nlen, op)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 928 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_get_vlen_element::nc_get_vlen_element (integer(c_int), value ncid, integer(c_int), value xtype, character(kind=c_char), dimension(*), intent(inout) vlen_element, integer(c_size_t), intent(inout) nlen, character(kind=c_char), dimension(*), intent(inout) op)"

.PP
Definition at line 929 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
