.TH "netcdf4_nf_interfaces::nf_inq_grp_parent" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_grp_parent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_grp_parent\fP (ncid, parent_ncid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 123 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_grp_parent::nf_inq_grp_parent (integer, intent(in) ncid, integer, intent(inout) parent_ncid)"

.PP
Definition at line 124 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
