.TH "netcdf4_nc_interfaces::nc_inq_enum" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_inq_enum
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_enum\fP (ncid, xtype, name, base_nc_typep, base_sizep, num_membersp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 638 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_inq_enum::nc_inq_enum (integer(c_int), value ncid, integer(c_int), value xtype, character(kind=c_char), dimension(*), intent(inout) name, integer(c_int), intent(inout) base_nc_typep, integer(c_size_t), intent(inout) base_sizep, integer(c_size_t), intent(inout) num_membersp)"

.PP
Definition at line 640 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
