.TH "netcdf4_nf_interfaces::nf_def_grp" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_def_grp
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_def_grp\fP (parent_ncid, name, new_ncid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 199 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_def_grp::nf_def_grp (integer, intent(in) parent_ncid, character(len=*), intent(in) name, integer, intent(out) new_ncid)"

.PP
Definition at line 200 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
