.TH "netcdf_nc_interfaces::nc_inq_var" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_inq_var
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_var\fP (ncid, varid, name, xtypep, ndimsp, dimidsp, nattsp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 530 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_inq_var::nc_inq_var (integer(c_int), value ncid, integer(c_int), value varid, character(kind=c_char), dimension(*), intent(out) name, integer(c_int), intent(out) xtypep, integer(c_int), intent(out) ndimsp, integer(c_int), dimension(*), intent(out) dimidsp, integer(c_int), intent(out) nattsp)"

.PP
Definition at line 532 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
