.TH "netcdf4_nc_interfaces::nc_insert_enum" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_insert_enum
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_insert_enum\fP (ncid, xtype, name, values)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 623 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_insert_enum::nc_insert_enum (integer(c_int), value ncid, integer(c_int), value xtype, character(kind=c_char), dimension(*), intent(in) name, type(c_ptr), value values)"

.PP
Definition at line 624 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
