.TH "netcdf4_func.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_func.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnf90_create_par\fP (path, cmode, comm, info, ncid, cache_size, cache_nelems, cache_preemption)"
.br
.ti -1c
.RI "integer function \fBnf90_open_par\fP (path, cmode, comm, info, ncid, cache_size, cache_nelems, cache_preemption)"
.br
.ti -1c
.RI "integer function \fBnf90_var_par_access\fP (ncid, varid, access)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_ncid\fP (ncid, name, grp_ncid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_grps\fP (ncid, numgrps, ncids)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_grpname_len\fP (ncid, len)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_grp_ncid\fP (ncid, name, grpid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_grp_full_ncid\fP (ncid, full_name, grpid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_grp_parent\fP (ncid, parent_ncid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_grpname\fP (ncid, name)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_grpname_full\fP (ncid, len, name)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_varids\fP (ncid, nvars, varids)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_dimids\fP (ncid, ndims, dimids, include_parents)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_typeids\fP (ncid, ntypes, typeids)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_typeid\fP (ncid, name, typeid)"
.br
.ti -1c
.RI "integer function \fBnf90_def_grp\fP (parent_ncid, name, new_ncid)"
.br
.ti -1c
.RI "integer function \fBnf90_rename_grp\fP (grpid, name)"
.br
.ti -1c
.RI "integer function \fBnf90_def_compound\fP (ncid, size, name, typeid)"
.br
.ti -1c
.RI "integer function \fBnf90_insert_compound\fP (ncid, xtype, name, offset, field_typeid)"
.br
.ti -1c
.RI "integer function \fBnf90_insert_array_compound\fP (ncid, xtype, name, offset, field_typeid, ndims, dim_sizes)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_type\fP (ncid, xtype, name, size)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound\fP (ncid, xtype, name, size, nfields)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound_name\fP (ncid, xtype, name)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound_size\fP (ncid, xtype, size)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound_nfields\fP (ncid, xtype, nfields)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound_field\fP (ncid, xtype, fieldid, name, offset, field_typeid, ndims, dim_sizes)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound_fieldname\fP (ncid, xtype, fieldid, name)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound_fieldindex\fP (ncid, xtype, name, fieldid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound_fieldoffset\fP (ncid, xtype, fieldid, offset)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound_fieldtype\fP (ncid, xtype, fieldid, field_typeid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_compound_fieldndims\fP (ncid, xtype, fieldid, ndims)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_cmp_fielddim_sizes\fP (ncid, xtype, fieldid, dim_sizes)"
.br
.ti -1c
.RI "integer function \fBnf90_def_vlen\fP (ncid, name, base_typeid, xtypeid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_vlen\fP (ncid, xtype, name, datum_size, base_nc_type)"
.br
.ti -1c
.RI "integer function \fBnf90_free_vlen\fP (vl)"
.br
.ti -1c
.RI "integer function \fBnf90_def_enum\fP (ncid, base_typeid, name, typeid)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_user_type\fP (ncid, xtype, name, size, base_typeid, nfields, class)"
.br
.ti -1c
.RI "integer function \fBnf90_insert_enum\fP (ncid, xtype, name, value)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_enum\fP (ncid, xtype, name, base_nc_type, base_size, num_members)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_enum_member\fP (ncid, xtype, idx, name, value)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_enum_ident\fP (ncid, xtype, value, idx)"
.br
.ti -1c
.RI "integer function \fBnf90_def_opaque\fP (ncid, size, name, xtype)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_opaque\fP (ncid, xtype, name, size)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_chunking\fP (ncid, varid, contiguous, chunksizes)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_deflate\fP (ncid, varid, shuffle, deflate, deflate_level)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_fletcher32\fP (ncid, varid, fletcher32)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_chunking\fP (ncid, varid, contiguous, chunksizes)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_deflate\fP (ncid, varid, shuffle, deflate, deflate_level)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_fletcher32\fP (ncid, varid, fletcher32)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_endian\fP (ncid, varid, endian)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_endian\fP (ncid, varid, endian)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_fill_onebyteint\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_fill_twobyteint\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_fill_fourbyteint\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_fill_eightbyteint\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_fill_fourbytereal\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_def_var_fill_eightbytereal\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_fill_onebyteint\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_fill_twobyteint\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_fill_fourbyteint\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_fill_eightbyteint\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_fill_fourbytereal\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_var_fill_eightbytereal\fP (ncid, varid, no_fill, fill)"
.br
.ti -1c
.RI "integer function \fBnf90_put_att_any\fP (ncid, varid, name, typeid, length, values)"
.br
.ti -1c
.RI "integer function \fBnf90_get_att_any\fP (ncid, varid, name, length, values)"
.br
.ti -1c
.RI "integer function \fBnf90_put_var_any\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_get_var_any\fP (ncid, varid, values, start, count, stride, map)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function nf90_create_par (character (len = *), intent(in) path, integer, intent(in) cmode, integer, intent(in) comm, integer, intent(in) info, integer, intent(out) ncid, integer, intent(in), optional cache_size, integer, intent(in), optional cache_nelems, real, intent(in), optional cache_preemption)"

.PP
Definition at line 7 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_compound (integer, intent(in) ncid, integer, intent(in) size, character (len = *), intent(in) name, integer, intent(out) typeid)"

.PP
Definition at line 230 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_enum (integer, intent(in) ncid, integer, intent(in) base_typeid, character (len = *), intent(in) name, integer, intent(out) typeid)"

.PP
Definition at line 418 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_grp (integer, intent(in) parent_ncid, character (len = *), intent(in) name, integer, intent(out) new_ncid)"

.PP
Definition at line 213 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_opaque (integer, intent(in) ncid, integer, intent(in) size, character (len = *), intent(in) name, integer, intent(out) xtype)"

.PP
Definition at line 484 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_chunking (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) contiguous, integer, dimension(:), intent(in) chunksizes)"

.PP
Definition at line 504 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_deflate (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) shuffle, integer, intent(in) deflate, integer, intent(in) deflate_level)"

.PP
Definition at line 514 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_endian (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) endian)"

.PP
Definition at line 564 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_fill_eightbyteint (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) no_fill, integer(kind=eightbyteint), intent(in) fill)"

.PP
Definition at line 632 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_fill_eightbytereal (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) no_fill, real(kind=eightbytereal), intent(in) fill)"

.PP
Definition at line 652 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_fill_fourbyteint (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) no_fill, integer(kind=fourbyteint), intent(in) fill)"

.PP
Definition at line 622 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_fill_fourbytereal (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) no_fill, real(kind=fourbytereal), intent(in) fill)"

.PP
Definition at line 642 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_fill_onebyteint (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) no_fill, integer(kind=onebyteint), intent(in) fill)"

.PP
Definition at line 602 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_fill_twobyteint (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) no_fill, integer(kind=twobyteint), intent(in) fill)"

.PP
Definition at line 612 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_var_fletcher32 (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) fletcher32)"

.PP
Definition at line 525 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_def_vlen (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(in) base_typeid, integer, intent(out) xtypeid)"

.PP
Definition at line 390 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_free_vlen (character (len = *), intent(in) vl)"

.PP
Definition at line 411 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_get_att_any (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer, intent(in) length, character(len = *), intent(in) values)"

.PP
Definition at line 732 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_get_var_any (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), intent(out) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 762 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_cmp_fielddim_sizes (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(in) fieldid, integer, intent(out) dim_sizes)"

.PP
Definition at line 380 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(out) name, integer, intent(out) size, integer, intent(out) nfields)"

.PP
Definition at line 276 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound_field (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(in) fieldid, character (len = *), intent(out) name, integer, intent(out) offset, integer, intent(out) field_typeid, integer, intent(out) ndims, integer, intent(out) dim_sizes)"

.PP
Definition at line 315 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound_fieldindex (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(in) name, integer, intent(out) fieldid)"

.PP
Definition at line 340 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound_fieldname (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(in) fieldid, character (len = *), intent(out) name)"

.PP
Definition at line 330 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound_fieldndims (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(in) fieldid, integer, intent(out) ndims)"

.PP
Definition at line 370 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound_fieldoffset (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(in) fieldid, integer, intent(out) offset)"

.PP
Definition at line 350 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound_fieldtype (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(in) fieldid, integer, intent(out) field_typeid)"

.PP
Definition at line 360 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound_name (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(out) name)"

.PP
Definition at line 287 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound_nfields (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(out) nfields)"

.PP
Definition at line 305 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_compound_size (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(out) size)"

.PP
Definition at line 296 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_dimids (integer, intent(in) ncid, integer, intent(out) ndims, integer, dimension(:), intent(out) dimids, integer, intent(out) include_parents)"

.PP
Definition at line 183 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_enum (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(out) name, integer, intent(out) base_nc_type, integer, intent(out) base_size, integer, intent(out) num_members)"

.PP
Definition at line 451 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_enum_ident (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(in) value, integer, intent(out) idx)"

.PP
Definition at line 474 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_enum_member (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(in) idx, character (len = *), intent(out) name, integer, intent(in) value)"

.PP
Definition at line 463 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_grp_full_ncid (integer, intent(in) ncid, character (len = *), intent(in) full_name, integer, intent(out) grpid)"

.PP
Definition at line 140 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_grp_ncid (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(out) grpid)"

.PP
Definition at line 131 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_grp_parent (integer, intent(in) ncid, integer, intent(out) parent_ncid)"

.PP
Definition at line 149 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_grpname (integer, intent(in) ncid, character (len = *), intent(out) name)"

.PP
Definition at line 157 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_grpname_full (integer, intent(in) ncid, integer, intent(out) len, character (len = *), intent(out) name)"

.PP
Definition at line 165 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_grpname_len (integer, intent(in) ncid, integer, intent(out) len)"

.PP
Definition at line 123 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_grps (integer, intent(in) ncid, integer, intent(out) numgrps, integer, dimension(:), intent(out) ncids)"

.PP
Definition at line 114 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_ncid (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(out) grp_ncid)"

.PP
Definition at line 105 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_opaque (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(out) name, integer, intent(out) size)"

.PP
Definition at line 494 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_type (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(out) name, integer, intent(out) size)"

.PP
Definition at line 266 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_typeid (integer, intent(in) ncid, character (len = *), intent(in) name, integer, intent(out), optional typeid)"

.PP
Definition at line 203 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_typeids (integer, intent(in) ncid, integer, intent(out), optional ntypes, integer, dimension(:), intent(out), optional typeids)"

.PP
Definition at line 193 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_user_type (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(out) name, integer, intent(out) size, integer, intent(out) base_typeid, integer, intent(out) nfields, integer, intent(out) class)"

.PP
Definition at line 428 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_chunking (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(out) contiguous, integer, dimension(:), intent(out) chunksizes)"

.PP
Definition at line 534 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_deflate (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(out) shuffle, integer, intent(out) deflate, integer, intent(out) deflate_level)"

.PP
Definition at line 544 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_endian (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(out) endian)"

.PP
Definition at line 573 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_fill_eightbyteint (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(inout) no_fill, integer(kind=eightbyteint), intent(inout) fill)"

.PP
Definition at line 692 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_fill_eightbytereal (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(inout) no_fill, real(kind=eightbytereal), intent(inout) fill)"

.PP
Definition at line 712 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_fill_fourbyteint (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(inout) no_fill, integer(kind=fourbyteint), intent(inout) fill)"

.PP
Definition at line 682 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_fill_fourbytereal (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(inout) no_fill, real(kind=fourbytereal), intent(inout) fill)"

.PP
Definition at line 702 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_fill_onebyteint (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(inout) no_fill, integer(kind=onebyteint), intent(inout) fill)"

.PP
Definition at line 662 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_fill_twobyteint (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(inout) no_fill, integer(kind=twobyteint), intent(inout) fill)"

.PP
Definition at line 672 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_var_fletcher32 (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(out) fletcher32)"

.PP
Definition at line 555 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_varids (integer, intent(in) ncid, integer, intent(out) nvars, integer, dimension(:), intent(out) varids)"

.PP
Definition at line 174 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_inq_vlen (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(out) name, integer, intent(out) datum_size, integer, intent(out) base_nc_type)"

.PP
Definition at line 400 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_insert_array_compound (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(in) name, integer, intent(in) offset, integer, intent(in) field_typeid, integer, intent(in) ndims, integer, intent(in) dim_sizes)"

.PP
Definition at line 252 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_insert_compound (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(in) name, integer, intent(in) offset, integer, intent(in) field_typeid)"

.PP
Definition at line 240 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_insert_enum (integer, intent(in) ncid, integer, intent(in) xtype, character (len = *), intent(in) name, integer, intent(in) value)"

.PP
Definition at line 441 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_open_par (character (len = *), intent(in) path, integer, intent(in) cmode, integer, intent(in) comm, integer, intent(in) info, integer, intent(out) ncid, integer, intent(in), optional cache_size, integer, intent(in), optional cache_nelems, real, intent(in), optional cache_preemption)"

.PP
Definition at line 52 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_put_att_any (integer, intent(in) ncid, integer, intent(in) varid, character(len = *), intent(in) name, integer, intent(in) typeid, integer, intent(in) length, character(len = *), intent(in) values)"

.PP
Definition at line 722 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_put_var_any (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), intent(in) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 742 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_rename_grp (integer, intent(in) grpid, character (len = *), intent(in) name)"

.PP
Definition at line 222 of file netcdf4_func\&.f90\&.
.SS "integer function nf90_var_par_access (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) access)"

.PP
Definition at line 96 of file netcdf4_func\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
