.TH "netcdf_nc_interfaces::addcnullchar" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::addcnullchar \- module procedure interfaces for utility routines  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "character(len=(len(string)+1)) function \fBaddcnullchar\fP (string, nlen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
module procedure interfaces for utility routines 
.PP
Definition at line 43 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "character(len=(len(string)+1)) function netcdf_nc_interfaces::addcnullchar::addcnullchar (character(len=*), intent(in) string, integer, intent(inout) nlen)"

.PP
Definition at line 2271 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
