.TH "netcdf_fortv2_c_interfaces::c_ncadel" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncadel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBc_ncadel\fP (ncid, varid, attname, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 558 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::c_ncadel::c_ncadel (integer(c_int), value ncid, integer(c_int), value varid, character(kind=c_char), dimension(*), intent(in) attname, integer(c_int), intent(out) rcode)"

.PP
Definition at line 559 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
