.TH "netcdf4_nc_interfaces::nc_put_vars_longlong" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_put_vars_longlong
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_put_vars_longlong\fP (ncid, varid, startp, countp, stridep, op)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1067 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_put_vars_longlong::nc_put_vars_longlong (integer(c_int), value ncid, integer(c_int), value varid, type(c_ptr), value startp, type(c_ptr), value countp, type(c_ptr), value stridep, integer(c_long_long), dimension(*), intent(in) op)"

.PP
Definition at line 1068 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
