.TH "netcdf4_nf_interfaces::nf_inq_compound_fieldoffset" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_compound_fieldoffset
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_inq_compound_fieldoffset\fP (ncid, xtype, fieldid, offset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 347 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf4_nf_interfaces::nf_inq_compound_fieldoffset::nf_inq_compound_fieldoffset (intent(in) ncid, intent(in) xtype, intent(in) fieldid, integer, intent(out) offset)"

.PP
Definition at line 351 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
