.TH "netcdf_nf_interfaces::nf_put_vara_double" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_put_vara_double
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_put_vara_double\fP (ncid, varid, start, counts, dvals)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1381 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf_nf_interfaces::nf_put_vara_double::nf_put_vara_double (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, real(rk8), dimension(*), intent(in) dvals)"

.PP
Definition at line 1385 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
