.TH "netcdf4_nc_interfaces::nc_open_par_fortran" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_open_par_fortran
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_open_par_fortran\fP (path, mode, comm, info, ncidp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_open_par_fortran::nc_open_par_fortran (character(kind=c_char), dimension(*), intent(in) path, integer(c_int), value mode, integer(c_int), value comm, integer(c_int), value info, integer(c_int), intent(out) ncidp)"

.PP
Definition at line 75 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
