.TH "netcdf4_nf_interfaces::nf_get_var1_int64" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_get_var1_int64
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_get_var1_int64\fP (ncid, varid, ndex, ival)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 800 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_get_var1_int64::nf_get_var1_int64 (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) ndex, integer(ik8), intent(out) ival)"

.PP
Definition at line 801 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
