.TH "netcdf4_nf_interfaces::nf_inq_user_type" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_user_type
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_user_type\fP (ncid, xtype, name, isize, base_type, nfields, iclass)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 413 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_user_type::nf_inq_user_type (integer, intent(in) ncid, integer, intent(in) xtype, character(len=*), intent(inout) name, integer, intent(out) isize, integer, intent(out) base_type, integer, intent(out) nfields, integer, intent(out) iclass)"

.PP
Definition at line 415 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
