.TH "netcdf_nf_interfaces::nf_copy_att" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_copy_att
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_copy_att\fP (ncid_in, varid_in, name, ncid_out, varid_out)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 586 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf_nf_interfaces::nf_copy_att::nf_copy_att (intent(in) ncid_in, intent(in) varid_in, character(len=*), intent(in) name, intent(in) ncid_out, intent(in) varid_out)"

.PP
Definition at line 590 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
