.TH "netcdf_nc_interfaces::nc_get_att_double" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_get_att_double
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_get_att_double\fP (ncid, varid, name, ip)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2227 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_get_att_double::nc_get_att_double (integer(c_int), value ncid, integer(c_int), value varid, character(kind=c_char), dimension(*), intent(in) name, real(c_double), dimension(*), intent(out) ip)"

.PP
Definition at line 2228 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
