.TH "netcdf4_nc_interfaces" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBnc_create_par_fortran\fP"
.br
.ti -1c
.RI "interface \fBnc_def_compound\fP"
.br
.ti -1c
.RI "interface \fBnc_def_enum\fP"
.br
.ti -1c
.RI "interface \fBnc_def_grp\fP"
.br
.ti -1c
.RI "interface \fBnc_def_opaque\fP"
.br
.ti -1c
.RI "interface \fBnc_def_var_chunking\fP"
.br
.ti -1c
.RI "interface \fBnc_def_var_chunking_ints\fP"
.br
.ti -1c
.RI "interface \fBnc_def_var_deflate\fP"
.br
.ti -1c
.RI "interface \fBnc_def_var_endian\fP"
.br
.ti -1c
.RI "interface \fBnc_def_var_fill\fP"
.br
.ti -1c
.RI "interface \fBnc_def_var_fletcher32\fP"
.br
.ti -1c
.RI "interface \fBnc_def_vlen\fP"
.br
.ti -1c
.RI "interface \fBnc_free_string\fP"
.br
.ti -1c
.RI "interface \fBnc_free_vlen\fP"
.br
.ti -1c
.RI "interface \fBnc_free_vlens\fP"
.br
.ti -1c
.RI "interface \fBnc_get_att\fP"
.br
.ti -1c
.RI "interface \fBnc_get_chunk_cache\fP"
.br
.ti -1c
.RI "interface \fBnc_get_chunk_cache_ints\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_chunk_cache_ints\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_get_varm_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vlen_element\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_field_f\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_field_ndims\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_fielddim_sizes\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_fieldindex\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_fieldname\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_fieldndims\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_fieldoffset\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_fieldtype\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_name\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_nfields\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_compound_size\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_dimids_f\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_enum\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_enum_ident\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_enum_member\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_grp_full_ncid\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_grp_ncid\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_grp_parent\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_grpname\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_grpname_full\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_grpname_len\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_grps\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_ncid\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_numgrps\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_numtypes\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_opaque\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_type\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_typeid\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_typeids\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_user_type\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_var_chunking\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_var_chunking_ints\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_var_deflate\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_var_endian\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_var_fill\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_var_fletcher32\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_var_szip\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_varids_f\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_vlen\fP"
.br
.ti -1c
.RI "interface \fBnc_insert_array_compound_f\fP"
.br
.ti -1c
.RI "interface \fBnc_insert_compound\fP"
.br
.ti -1c
.RI "interface \fBnc_insert_enum\fP"
.br
.ti -1c
.RI "interface \fBnc_open_par_fortran\fP"
.br
.ti -1c
.RI "interface \fBnc_put_att\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_put_varm_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars_longlong\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vlen_element\fP"
.br
.ti -1c
.RI "interface \fBnc_rename_grp\fP"
.br
.ti -1c
.RI "interface \fBnc_set_chunk_cache\fP"
.br
.ti -1c
.RI "interface \fBnc_set_chunk_cache_ints\fP"
.br
.ti -1c
.RI "interface \fBnc_set_var_chunk_cache_ints\fP"
.br
.ti -1c
.RI "interface \fBnc_var_par_access\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
