.TH "netcdf4_nf_interfaces::nf_inq_compound_field" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_compound_field
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_compound_field\fP (ncid, xtype, fieldid, name, offset, field_typeid, ndims, dim_sizes)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 312 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_compound_field::nf_inq_compound_field (integer, intent(in) ncid, integer, intent(in) xtype, integer, intent(in) fieldid, character(len=*), intent(out) name, integer, intent(out) offset, integer, intent(out) field_typeid, integer, intent(out) ndims, integer, dimension(*), intent(out) dim_sizes)"

.PP
Definition at line 314 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
