.TH "netcdf_nf_interfaces::nf_rename_dim" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_rename_dim
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_rename_dim\fP (ncid, dimid, name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 348 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf_nf_interfaces::nf_rename_dim::nf_rename_dim (integer, intent(in) ncid, integer, intent(in) dimid, character(len=*), intent(in) name)"

.PP
Definition at line 349 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
