.TH "netcdf_overloads.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_overloads.f90
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBnf90_def_var\fP"
.br
.ti -1c
.RI "interface \fBnf90_put_att\fP"
.br
.ti -1c
.RI "interface \fBnf90_get_att\fP"
.br
.ti -1c
.RI "interface \fBnf90_put_var\fP"
.br
.ti -1c
.RI "interface \fBnf90_get_var\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
