.TH "netcdf4_nf_interfaces::nf_inq_grpname_len" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_grpname_len
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_grpname_len\fP (ncid, nlen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_grpname_len::nf_inq_grpname_len (integer, intent(in) ncid, integer, intent(out) nlen)"

.PP
Definition at line 114 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
