.TH "netcdf4_nf_interfaces::nf_inq_grps" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_grps
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_grps\fP (ncid, numgrps, ncids)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_grps::nf_inq_grps (integer, intent(in) ncid, integer, intent(out) numgrps, integer, dimension(*), intent(inout) ncids)"

.PP
Definition at line 82 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
