.TH "netcdf4_nf_interfaces::nf_inq_grp_full_ncid" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_grp_full_ncid
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_grp_full_ncid\fP (ncid, grp_name, grp_ncid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 133 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_grp_full_ncid::nf_inq_grp_full_ncid (integer, intent(in) ncid, character(len=*), intent(in) grp_name, integer, intent(inout) grp_ncid)"

.PP
Definition at line 134 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
