.TH "netcdf_nf_interfaces::nf_put_att_int2" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_interfaces::nf_put_att_int2
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "function \fBnf_put_att_int2\fP (ncid, varid, name, xtype, nlen, i2vals)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1514 of file module_netcdf_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "function netcdf_nf_interfaces::nf_put_att_int2::nf_put_att_int2 (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(in) xtype, integer, intent(in) nlen, integer(nfint2), dimension(*), intent(in) i2vals)"

.PP
Definition at line 1518 of file module_netcdf_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
