.TH "netcdf_fortv2_c_interfaces::c_ncddef" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncddef
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBc_ncddef\fP (ncid, dimname, dimlen, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_fortv2_c_interfaces::c_ncddef::c_ncddef (integer(c_int), value ncid, character(kind=c_char), dimension(*), intent(in) dimname, integer(c_int), value dimlen, integer(c_int), intent(out) rcode)"

.PP
Definition at line 101 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
