.TH "netcdf_fortv2_c_interfaces::c_ncvgtg" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncvgtg
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBc_ncvgtg\fP (ncid, varid, start, count, strides, imap, value, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 409 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::c_ncvgtg::c_ncvgtg (integer(c_int), value ncid, integer(c_int), value varid, type(c_ptr), value start, type(c_ptr), value count, type(c_ptr), value strides, type(c_ptr), value imap, character(kind=c_char), dimension(*), intent(out) value, integer(c_int), intent(out) rcode)"

.PP
Definition at line 411 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
