.TH "netcdf_text_variables.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_text_variables.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnf90_put_var_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_get_var_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_put_var_1d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_put_var_2d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_put_var_3d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_put_var_4d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_put_var_5d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_put_var_6d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_put_var_7d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_get_var_1d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_get_var_2d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_get_var_3d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_get_var_4d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_get_var_5d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_get_var_6d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.ti -1c
.RI "integer function \fBnf90_get_var_7d_text\fP (ncid, varid, values, start, count, stride, map)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function nf90_get_var_1d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:), intent(out) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 269 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_get_var_2d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :), intent(out) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 301 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_get_var_3d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :), intent(out) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 333 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_get_var_4d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :, :), intent(out) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 365 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_get_var_5d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :, :, :), intent(out) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 397 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_get_var_6d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :, :, :, :), intent(out) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 429 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_get_var_7d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :, :, :, :, :), intent(out) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 461 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_get_var_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), intent(out) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 22 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_put_var_1d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:), intent(in) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 45 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_put_var_2d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :), intent(in) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 77 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_put_var_3d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :), intent(in) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 109 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_put_var_4d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :, :), intent(in) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 141 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_put_var_5d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :, :, :), intent(in) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 173 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_put_var_6d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :, :, :, :), intent(in) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 205 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_put_var_7d_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), dimension(:, :, :, :, :, :, :), intent(in) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 237 of file netcdf_text_variables\&.f90\&.
.SS "integer function nf90_put_var_text (integer, intent(in) ncid, integer, intent(in) varid, character (len = *), intent(in) values, integer, dimension(:), intent(in), optional start, integer, dimension(:), intent(in), optional count, integer, dimension(:), intent(in), optional stride, integer, dimension(:), intent(in), optional map)"

.PP
Definition at line 2 of file netcdf_text_variables\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
