.TH "netcdf4_nc_interfaces::nc_inq_dimids_f" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_inq_dimids_f
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_dimids_f\fP (ncid, ndims, dimids, parent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 249 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_inq_dimids_f::nc_inq_dimids_f (integer(c_int), value ncid, integer(c_int), intent(inout) ndims, integer(c_int), dimension(*), intent(inout) dimids, integer(c_int), value parent)"

.PP
Definition at line 250 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
