.TH "netcdf_file.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_file.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "character(len=80) function \fBnf90_inq_libvers\fP ()"
.br
.ti -1c
.RI "character(len=80) function \fBnf90_strerror\fP (ncerr)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_base_pe\fP (ncid, pe)"
.br
.ti -1c
.RI "integer function \fBnf90_set_base_pe\fP (ncid, pe)"
.br
.ti -1c
.RI "integer function \fBnf90_create_mp\fP (path, cmode, initalsz, basepe, chunksizehint, ncid)"
.br
.ti -1c
.RI "integer function \fBnf90_open_mp\fP (path, mode, basepe, chunksizeint, ncid)"
.br
.ti -1c
.RI "integer function \fBnf90_set_fill\fP (ncid, fillmode, old_mode)"
.br
.ti -1c
.RI "integer function \fBnf90_redef\fP (ncid)"
.br
.ti -1c
.RI "integer function \fBnf90_enddef\fP (ncid, h_minfree, v_align, v_minfree, r_align)"
.br
.ti -1c
.RI "integer function \fBnf90_sync\fP (ncid)"
.br
.ti -1c
.RI "integer function \fBnf90_abort\fP (ncid)"
.br
.ti -1c
.RI "integer function \fBnf90_close\fP (ncid)"
.br
.ti -1c
.RI "integer function \fBnf90_delete\fP (name)"
.br
.ti -1c
.RI "integer function \fBnf90_inquire\fP (ncid, nDimensions, nVariables, nAttributes, unlimitedDimId, formatNum)"
.br
.ti -1c
.RI "integer function \fBnf90_inq_path\fP (ncid, pathlen, path)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function nf90_abort (integer, intent(in) ncid)"

.PP
Definition at line 103 of file netcdf_file\&.f90\&.
.SS "integer function nf90_close (integer, intent(in) ncid)"

.PP
Definition at line 110 of file netcdf_file\&.f90\&.
.SS "integer function nf90_create_mp (character (len = *), intent(in) path, integer, intent(in) cmode, integer, intent(in) initalsz, integer, intent(in) basepe, integer, intent(in) chunksizehint, integer, intent(out) ncid)"

.PP
Definition at line 41 of file netcdf_file\&.f90\&.
.SS "integer function nf90_delete (character(len = *), intent(in) name)"

.PP
Definition at line 117 of file netcdf_file\&.f90\&.
.SS "integer function nf90_enddef (integer, intent(in) ncid, integer, intent(in), optional h_minfree, integer, intent(in), optional v_align, integer, intent(in), optional v_minfree, integer, intent(in), optional r_align)"

.PP
Definition at line 74 of file netcdf_file\&.f90\&.
.SS "integer function nf90_inq_base_pe (integer, intent(in) ncid, integer, intent(out) pe)"

.PP
Definition at line 26 of file netcdf_file\&.f90\&.
.SS "character(len = 80) function nf90_inq_libvers ()"

.PP
Definition at line 10 of file netcdf_file\&.f90\&.
.SS "integer function nf90_inq_path (integer, intent(in) ncid, integer, intent(inout) pathlen, character(len = *), intent(inout) path)"

.PP
Definition at line 145 of file netcdf_file\&.f90\&.
.SS "integer function nf90_inquire (integer, intent(in) ncid, integer, intent(out), optional nDimensions, integer, intent(out), optional nVariables, integer, intent(out), optional nAttributes, integer, intent(out), optional unlimitedDimId, integer, intent(out), optional formatNum)"

.PP
Definition at line 127 of file netcdf_file\&.f90\&.
.SS "integer function nf90_open_mp (character (len = *), intent(in) path, integer, intent(in) mode, integer, intent(in) basepe, integer, intent(in) chunksizeint, integer, intent(out) ncid)"

.PP
Definition at line 50 of file netcdf_file\&.f90\&.
.SS "integer function nf90_redef (integer, intent(in) ncid)"

.PP
Definition at line 67 of file netcdf_file\&.f90\&.
.SS "integer function nf90_set_base_pe (integer, intent(in) ncid, integer, intent(in) pe)"

.PP
Definition at line 34 of file netcdf_file\&.f90\&.
.SS "integer function nf90_set_fill (integer, intent(in) ncid, integer, intent(in) fillmode, integer, intent(out) old_mode)"

.PP
Definition at line 59 of file netcdf_file\&.f90\&.
.SS "character(len = 80) function nf90_strerror (integer, intent(in) ncerr)"

.PP
Definition at line 16 of file netcdf_file\&.f90\&.
.SS "integer function nf90_sync (integer, intent(in) ncid)"

.PP
Definition at line 96 of file netcdf_file\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
