.TH "netcdf_fortv2_c_interfaces::c_ncdinq" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncdinq
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBc_ncdinq\fP (ncid, dimid, dimname, size, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 238 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::c_ncdinq::c_ncdinq (integer(c_int), value ncid, integer(c_int), value dimid, character(kind=c_char), dimension(*), intent(out) dimname, integer(c_int), intent(out) size, integer(c_int), intent(out) rcode)"

.PP
Definition at line 239 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
