.TH "netcdf_nc_interfaces::nc_inq_varid" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_inq_varid
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_varid\fP (ncid, name, varidp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 548 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_inq_varid::nc_inq_varid (integer(c_int), value ncid, character(kind=c_char), dimension(*), intent(in) name, integer(c_int), intent(out) varidp)"

.PP
Definition at line 549 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
