.TH "netcdf4_nc_interfaces::nc_inq_compound_field_f" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_inq_compound_field_f
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_inq_compound_field_f\fP (ncid, xtype, fieldid, name, offsetp, field_typeidp, ndimsp, dim_sizesp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 454 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_inq_compound_field_f::nc_inq_compound_field_f (integer(c_int), value ncid, integer(c_int), value xtype, integer(c_int), value fieldid, character(kind=c_char), dimension(*), intent(inout) name, integer(c_size_t), intent(inout) offsetp, integer(c_int), intent(inout) field_typeidp, integer(c_int), intent(inout) ndimsp, integer(c_int), dimension(*), intent(inout) dim_sizesp)"

.PP
Definition at line 456 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
