.TH "netcdf_nf_data" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nf_data
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBnf_nat\fP = NC_NAT"
.br
.ti -1c
.RI "integer, parameter \fBnf_byte\fP = NC_BYTE"
.br
.ti -1c
.RI "integer, parameter \fBnf_int1\fP = NF_BYTE"
.br
.ti -1c
.RI "integer, parameter \fBnf_char\fP = NC_CHAR"
.br
.ti -1c
.RI "integer, parameter \fBnf_short\fP = NC_SHORT"
.br
.ti -1c
.RI "integer, parameter \fBnf_int2\fP = NF_SHORT"
.br
.ti -1c
.RI "integer, parameter \fBnf_int\fP = NC_INT"
.br
.ti -1c
.RI "integer, parameter \fBnf_float\fP = NC_FLOAT"
.br
.ti -1c
.RI "integer, parameter \fBnf_real\fP = NF_FLOAT"
.br
.ti -1c
.RI "integer, parameter \fBnf_double\fP = NC_DOUBLE"
.br
.ti -1c
.RI "integer, parameter \fBnf_fill_char\fP = IACHAR(NC_FILL_CHAR)"
.br
.ti -1c
.RI "integer(ik1), parameter \fBnf_fill_byte\fP = NC_FILL_BYTE"
.br
.ti -1c
.RI "integer(ik2), parameter \fBnf_fill_short\fP = NC_FILL_SHORT"
.br
.ti -1c
.RI "integer, parameter \fBnf_fill_int\fP = NC_FILL_INT"
.br
.ti -1c
.RI "real(rk4), parameter \fBnf_fill_float\fP = NC_FILL_FLOAT"
.br
.ti -1c
.RI "real(rk4), parameter \fBnf_fill_real\fP = NF_FILL_FLOAT"
.br
.ti -1c
.RI "real(rk4), parameter \fBnf_fill_real4\fP = NF_FILL_FLOAT"
.br
.ti -1c
.RI "real(rk8), parameter \fBnf_fill_double\fP = NC_FILL_DOUBLE"
.br
.ti -1c
.RI "real(rk8), parameter \fBnf_fill_real8\fP = NF_FILL_DOUBLE"
.br
.ti -1c
.RI "integer, parameter \fBnf_nowrite\fP = NC_NOWRITE"
.br
.ti -1c
.RI "integer, parameter \fBnf_write\fP = NC_WRITE"
.br
.ti -1c
.RI "integer, parameter \fBnf_clobber\fP = NC_CLOBBER"
.br
.ti -1c
.RI "integer, parameter \fBnf_noclobber\fP = NC_NOCLOBBER"
.br
.ti -1c
.RI "integer, parameter \fBnf_fill\fP = NC_FILL"
.br
.ti -1c
.RI "integer, parameter \fBnf_nofill\fP = NC_NOFILL"
.br
.ti -1c
.RI "integer, parameter \fBnf_lock\fP = NC_LOCK"
.br
.ti -1c
.RI "integer, parameter \fBnf_share\fP = NC_SHARE"
.br
.ti -1c
.RI "integer, parameter \fBnf_strict_nc3\fP = NC_STRICT_NC3"
.br
.ti -1c
.RI "integer, parameter \fBnf_64bit_offset\fP = NC_64BIT_OFFSET"
.br
.ti -1c
.RI "integer, parameter \fBnf_sizehint_default\fP = NC_SIZEHINT_DEFAULT"
.br
.ti -1c
.RI "integer, parameter \fBnf_align_chunk\fP = NC_ALIGN_CHUNK"
.br
.ti -1c
.RI "integer, parameter \fBnf_format_classic\fP = NC_FORMAT_CLASSIC"
.br
.ti -1c
.RI "integer, parameter \fBnf_format_64bit\fP = NC_FORMAT_64BIT"
.br
.ti -1c
.RI "integer, parameter \fBnf_diskless\fP = NC_DISKLESS"
.br
.ti -1c
.RI "integer, parameter \fBnf_mmap\fP = NC_MMAP"
.br
.ti -1c
.RI "integer, parameter \fBnf_inmemory\fP = NC_INMEMORY"
.br
.ti -1c
.RI "integer, parameter \fBnf_unlimited\fP = NC_UNLIMITED"
.br
.ti -1c
.RI "integer, parameter \fBnf_global\fP = NC_GLOBAL"
.br
.ti -1c
.RI "integer, parameter \fBnf_max_dims\fP = NC_MAX_DIMS"
.br
.ti -1c
.RI "integer, parameter \fBnf_max_attrs\fP = NC_MAX_ATTRS"
.br
.ti -1c
.RI "integer, parameter \fBnf_max_vars\fP = NC_MAX_VARS"
.br
.ti -1c
.RI "integer, parameter \fBnf_max_name\fP = NC_MAX_NAME"
.br
.ti -1c
.RI "integer, parameter \fBnf_max_var_dims\fP = NC_MAX_DIMS"
.br
.ti -1c
.RI "integer, parameter \fBnf_noerr\fP = NC_NOERR"
.br
.ti -1c
.RI "integer, parameter \fBnf2_err\fP = NC2_ERR"
.br
.ti -1c
.RI "integer, parameter \fBnf_syserr\fP = NC_SYSERR"
.br
.ti -1c
.RI "integer, parameter \fBnf_exdr\fP = NC_EXDR"
.br
.ti -1c
.RI "integer, parameter \fBnf_ebadid\fP = NC_EBADID"
.br
.ti -1c
.RI "integer, parameter \fBnf_ebfile\fP = NC_EBFILE"
.br
.ti -1c
.RI "integer, parameter \fBnf_eexist\fP = NC_EEXIST"
.br
.ti -1c
.RI "integer, parameter \fBnf_einval\fP = NC_EINVAL"
.br
.ti -1c
.RI "integer, parameter \fBnf_eperm\fP = NC_EPERM"
.br
.ti -1c
.RI "integer, parameter \fBnf_enotindefine\fP = NC_ENOTINDEFINE"
.br
.ti -1c
.RI "integer, parameter \fBnf_eindefine\fP = NC_EINDEFINE"
.br
.ti -1c
.RI "integer, parameter \fBnf_einvalcoords\fP = NC_EINVALCOORDS"
.br
.ti -1c
.RI "integer, parameter \fBnf_emaxdims\fP = NC_EMAXDIMS"
.br
.ti -1c
.RI "integer, parameter \fBnf_enameinuse\fP = NC_ENAMEINUSE"
.br
.ti -1c
.RI "integer, parameter \fBnf_enotatt\fP = NC_ENOTATT"
.br
.ti -1c
.RI "integer, parameter \fBnf_emaxatts\fP = NC_EMAXATTS"
.br
.ti -1c
.RI "integer, parameter \fBnf_ebadtype\fP = NC_EBADTYPE"
.br
.ti -1c
.RI "integer, parameter \fBnf_ebaddim\fP = NC_EBADDIM"
.br
.ti -1c
.RI "integer, parameter \fBnf_eunlimpos\fP = NC_EUNLIMPOS"
.br
.ti -1c
.RI "integer, parameter \fBnf_emaxvars\fP = NC_EMAXVARS"
.br
.ti -1c
.RI "integer, parameter \fBnf_enotvar\fP = NC_ENOTVAR"
.br
.ti -1c
.RI "integer, parameter \fBnf_eglobal\fP = NC_EGLOBAL"
.br
.ti -1c
.RI "integer, parameter \fBnf_enotnc\fP = NC_ENOTNC"
.br
.ti -1c
.RI "integer, parameter \fBnf_ests\fP = NC_ESTS"
.br
.ti -1c
.RI "integer, parameter \fBnf_emaxname\fP = NC_EMAXNAME"
.br
.ti -1c
.RI "integer, parameter \fBnf_eunlimit\fP = NC_EUNLIMIT"
.br
.ti -1c
.RI "integer, parameter \fBnf_enorecvars\fP = NC_ENORECVARS"
.br
.ti -1c
.RI "integer, parameter \fBnf_echar\fP = NC_ECHAR"
.br
.ti -1c
.RI "integer, parameter \fBnf_eedge\fP = NC_EEDGE"
.br
.ti -1c
.RI "integer, parameter \fBnf_estride\fP = NC_ESTRIDE"
.br
.ti -1c
.RI "integer, parameter \fBnf_ebadname\fP = NC_EBADNAME"
.br
.ti -1c
.RI "integer, parameter \fBnf_erange\fP = NC_ERANGE"
.br
.ti -1c
.RI "integer, parameter \fBnf_enomem\fP = NC_ENOMEM"
.br
.ti -1c
.RI "integer, parameter \fBnf_evarsize\fP = NC_EVARSIZE"
.br
.ti -1c
.RI "integer, parameter \fBnf_edimsize\fP = NC_EDIMSIZE"
.br
.ti -1c
.RI "integer, parameter \fBnf_etrunc\fP = NC_ETRUNC"
.br
.ti -1c
.RI "integer, parameter \fBnf_eaxistype\fP = NC_EAXISTYPE"
.br
.ti -1c
.RI "integer, parameter \fBnf_edap\fP = NC_EDAP"
.br
.ti -1c
.RI "integer, parameter \fBnf_ecurl\fP = NC_ECURL"
.br
.ti -1c
.RI "integer, parameter \fBnf_eio\fP = NC_EIO"
.br
.ti -1c
.RI "integer, parameter \fBnf_enodata\fP = NC_ENODATA"
.br
.ti -1c
.RI "integer, parameter \fBnf_edapsvc\fP = NC_EDAPSVC"
.br
.ti -1c
.RI "integer, parameter \fBnf_edas\fP = NC_EDAS"
.br
.ti -1c
.RI "integer, parameter \fBnf_edds\fP = NC_EDDS"
.br
.ti -1c
.RI "integer, parameter \fBnf_edatadds\fP = NC_EDATADDS"
.br
.ti -1c
.RI "integer, parameter \fBnf_edapurl\fP = NC_EDAPURL"
.br
.ti -1c
.RI "integer, parameter \fBnf_edapconstraint\fP = NC_EDAPCONSTRAINT"
.br
.ti -1c
.RI "integer, parameter \fBnf_etranslation\fP = NC_ETRANSLATION"
.br
.ti -1c
.RI "integer, parameter \fBnf_fatal\fP = NC_FATAL"
.br
.ti -1c
.RI "integer, parameter \fBnf_verbose\fP = NC_VERBOSE"
.br
.ti -1c
.RI "integer, parameter \fBncbyte\fP = NF_BYTE"
.br
.ti -1c
.RI "integer, parameter \fBncchar\fP = NF_CHAR"
.br
.ti -1c
.RI "integer, parameter \fBncshort\fP = NF_SHORT"
.br
.ti -1c
.RI "integer, parameter \fBnclong\fP = \fBNF_INT\fP"
.br
.ti -1c
.RI "integer, parameter \fBncfloat\fP = NF_FLOAT"
.br
.ti -1c
.RI "integer, parameter \fBncdouble\fP = NF_DOUBLE"
.br
.ti -1c
.RI "integer, parameter \fBncrdwr\fP = NF_WRITE"
.br
.ti -1c
.RI "integer, parameter \fBnccreate\fP = 2"
.br
.ti -1c
.RI "integer, parameter \fBncexcl\fP = 4"
.br
.ti -1c
.RI "integer, parameter \fBncindef\fP = 8"
.br
.ti -1c
.RI "integer, parameter \fBncnsync\fP = 16"
.br
.ti -1c
.RI "integer, parameter \fBnchsync\fP = 32"
.br
.ti -1c
.RI "integer, parameter \fBncndirty\fP = 64"
.br
.ti -1c
.RI "integer, parameter \fBnchdirty\fP = 128"
.br
.ti -1c
.RI "integer, parameter \fBncfill\fP = NF_FILL"
.br
.ti -1c
.RI "integer, parameter \fBncnofill\fP = NF_NOFILL"
.br
.ti -1c
.RI "integer, parameter \fBnclink\fP = 32768"
.br
.ti -1c
.RI "integer, parameter \fBncnowrit\fP = NF_NOWRITE"
.br
.ti -1c
.RI "integer, parameter \fBncwrite\fP = NF_WRITE"
.br
.ti -1c
.RI "integer, parameter \fBncclob\fP = NF_CLOBBER"
.br
.ti -1c
.RI "integer, parameter \fBncnoclob\fP = NF_NOCLOBBER"
.br
.ti -1c
.RI "integer, parameter \fBncunlim\fP = NF_UNLIMITED"
.br
.ti -1c
.RI "integer, parameter \fBncglobal\fP = NF_GLOBAL"
.br
.ti -1c
.RI "integer, parameter \fBmaxncop\fP = 64"
.br
.ti -1c
.RI "integer, parameter \fBmaxncdim\fP = NF_MAX_DIMS"
.br
.ti -1c
.RI "integer, parameter \fBmaxncatt\fP = NF_MAX_ATTRS"
.br
.ti -1c
.RI "integer, parameter \fBmaxncvar\fP = NF_MAX_VARS"
.br
.ti -1c
.RI "integer, parameter \fBmaxncnam\fP = NF_MAX_NAME"
.br
.ti -1c
.RI "integer, parameter \fBmaxvdims\fP = MAXNCDIM"
.br
.ti -1c
.RI "integer, parameter \fBncnoerr\fP = NF_NOERR"
.br
.ti -1c
.RI "integer, parameter \fBncebadid\fP = NF_EBADID"
.br
.ti -1c
.RI "integer, parameter \fBncenfile\fP = \-31"
.br
.ti -1c
.RI "integer, parameter \fBnceexist\fP = NF_EEXIST"
.br
.ti -1c
.RI "integer, parameter \fBnceinval\fP = NF_EINVAL"
.br
.ti -1c
.RI "integer, parameter \fBnceperm\fP = NF_EPERM"
.br
.ti -1c
.RI "integer, parameter \fBncenotin\fP = NF_ENOTINDEFINE"
.br
.ti -1c
.RI "integer, parameter \fBnceindef\fP = NF_EINDEFINE"
.br
.ti -1c
.RI "integer, parameter \fBncecoord\fP = NF_EINVALCOORDS"
.br
.ti -1c
.RI "integer, parameter \fBncemaxds\fP = NF_EMAXDIMS"
.br
.ti -1c
.RI "integer, parameter \fBncename\fP = NF_ENAMEINUSE"
.br
.ti -1c
.RI "integer, parameter \fBncemaxat\fP = NF_EMAXATTS"
.br
.ti -1c
.RI "integer, parameter \fBncebadty\fP = NF_EBADTYPE"
.br
.ti -1c
.RI "integer, parameter \fBncebadd\fP = NF_EBADDIM"
.br
.ti -1c
.RI "integer, parameter \fBnceunlim\fP = NF_EUNLIMPOS"
.br
.ti -1c
.RI "integer, parameter \fBncemaxvs\fP = NF_EMAXVARS"
.br
.ti -1c
.RI "integer, parameter \fBncenotvr\fP = NF_ENOTVAR"
.br
.ti -1c
.RI "integer, parameter \fBnceglob\fP = NF_EGLOBAL"
.br
.ti -1c
.RI "integer, parameter \fBncnotnc\fP = NF_ENOTNC"
.br
.ti -1c
.RI "integer, parameter \fBncestc\fP = NF_ESTS"
.br
.ti -1c
.RI "integer, parameter \fBncentool\fP = NF_EMAXNAME"
.br
.ti -1c
.RI "integer, parameter \fBncfoobar\fP = 32"
.br
.ti -1c
.RI "integer, parameter \fBncsyserr\fP = NF_SYSERR"
.br
.ti -1c
.RI "integer, parameter \fBncfatal\fP = NF_FATAL"
.br
.ti -1c
.RI "integer, parameter \fBncverbos\fP = NF_VERBOSE"
.br
.ti -1c
.RI "integer, parameter \fBfilchar\fP = NF_FILL_CHAR"
.br
.ti -1c
.RI "integer(ik1), parameter \fBfilbyte\fP = NF_FILL_BYTE"
.br
.ti -1c
.RI "integer(ik2), parameter \fBfilshort\fP = NF_FILL_SHORT"
.br
.ti -1c
.RI "integer, parameter \fBfillong\fP = NF_FILL_INT"
.br
.ti -1c
.RI "real(rk4), parameter \fBfilfloat\fP = NF_FILL_FLOAT"
.br
.ti -1c
.RI "real(rk8), parameter \fBfildoub\fP = NF_FILL_DOUBLE"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "integer(ik1), parameter netcdf_nf_data::filbyte = NF_FILL_BYTE"

.PP
Definition at line 336 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::filchar = NF_FILL_CHAR"

.PP
Definition at line 335 of file module_netcdf_nf_data\&.F90\&.
.SS "real(rk8), parameter netcdf_nf_data::fildoub = NF_FILL_DOUBLE"

.PP
Definition at line 340 of file module_netcdf_nf_data\&.F90\&.
.SS "real(rk4), parameter netcdf_nf_data::filfloat = NF_FILL_FLOAT"

.PP
Definition at line 339 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::fillong = NF_FILL_INT"

.PP
Definition at line 338 of file module_netcdf_nf_data\&.F90\&.
.SS "integer(ik2), parameter netcdf_nf_data::filshort = NF_FILL_SHORT"

.PP
Definition at line 337 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::maxncatt = NF_MAX_ATTRS"

.PP
Definition at line 303 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::maxncdim = NF_MAX_DIMS"

.PP
Definition at line 302 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::maxncnam = NF_MAX_NAME"

.PP
Definition at line 305 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::maxncop = 64"

.PP
Definition at line 301 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::maxncvar = NF_MAX_VARS"

.PP
Definition at line 304 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::maxvdims = MAXNCDIM"

.PP
Definition at line 306 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncbyte = NF_BYTE"

.PP
Definition at line 274 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncchar = NF_CHAR"

.PP
Definition at line 275 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncclob = NF_CLOBBER"

.PP
Definition at line 295 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nccreate = 2"

.PP
Definition at line 282 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncdouble = NF_DOUBLE"

.PP
Definition at line 279 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncebadd = NF_EBADDIM"

.PP
Definition at line 321 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncebadid = NF_EBADID"

.PP
Definition at line 309 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncebadty = NF_EBADTYPE"

.PP
Definition at line 320 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncecoord = NF_EINVALCOORDS"

.PP
Definition at line 316 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nceexist = NF_EEXIST"

.PP
Definition at line 311 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nceglob = NF_EGLOBAL"

.PP
Definition at line 325 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nceindef = NF_EINDEFINE"

.PP
Definition at line 315 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nceinval = NF_EINVAL"

.PP
Definition at line 312 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncemaxat = NF_EMAXATTS"

.PP
Definition at line 319 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncemaxds = NF_EMAXDIMS"

.PP
Definition at line 317 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncemaxvs = NF_EMAXVARS"

.PP
Definition at line 323 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncename = NF_ENAMEINUSE"

.PP
Definition at line 318 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncenfile = \-31"

.PP
Definition at line 310 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncenotin = NF_ENOTINDEFINE"

.PP
Definition at line 314 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncenotvr = NF_ENOTVAR"

.PP
Definition at line 324 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncentool = NF_EMAXNAME"

.PP
Definition at line 328 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nceperm = NF_EPERM"

.PP
Definition at line 313 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncestc = NF_ESTS"

.PP
Definition at line 327 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nceunlim = NF_EUNLIMPOS"

.PP
Definition at line 322 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncexcl = 4"

.PP
Definition at line 283 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncfatal = NF_FATAL"

.PP
Definition at line 332 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncfill = NF_FILL"

.PP
Definition at line 289 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncfloat = NF_FLOAT"

.PP
Definition at line 278 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncfoobar = 32"

.PP
Definition at line 329 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncglobal = NF_GLOBAL"

.PP
Definition at line 299 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nchdirty = 128"

.PP
Definition at line 288 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nchsync = 32"

.PP
Definition at line 286 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncindef = 8"

.PP
Definition at line 284 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nclink = 32768"

.PP
Definition at line 291 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nclong = \fBNF_INT\fP"

.PP
Definition at line 277 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncndirty = 64"

.PP
Definition at line 287 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncnoclob = NF_NOCLOBBER"

.PP
Definition at line 296 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncnoerr = NF_NOERR"

.PP
Definition at line 308 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncnofill = NF_NOFILL"

.PP
Definition at line 290 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncnotnc = NF_ENOTNC"

.PP
Definition at line 326 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncnowrit = NF_NOWRITE"

.PP
Definition at line 293 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncnsync = 16"

.PP
Definition at line 285 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncrdwr = NF_WRITE"

.PP
Definition at line 281 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncshort = NF_SHORT"

.PP
Definition at line 276 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncsyserr = NF_SYSERR"

.PP
Definition at line 330 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncunlim = NF_UNLIMITED"

.PP
Definition at line 298 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncverbos = NF_VERBOSE"

.PP
Definition at line 333 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::ncwrite = NF_WRITE"

.PP
Definition at line 294 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf2_err = NC2_ERR"

.PP
Definition at line 111 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_64bit_offset = NC_64BIT_OFFSET"

.PP
Definition at line 86 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_align_chunk = NC_ALIGN_CHUNK"

.PP
Definition at line 88 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_byte = NC_BYTE"

.PP
Definition at line 52 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_char = NC_CHAR"

.PP
Definition at line 54 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_clobber = NC_CLOBBER"

.PP
Definition at line 79 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_diskless = NC_DISKLESS"

.PP
Definition at line 91 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_double = NC_DOUBLE"

.PP
Definition at line 60 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_eaxistype = NC_EAXISTYPE"

.PP
Definition at line 147 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_ebaddim = NC_EBADDIM"

.PP
Definition at line 127 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_ebadid = NC_EBADID"

.PP
Definition at line 114 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_ebadname = NC_EBADNAME"

.PP
Definition at line 141 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_ebadtype = NC_EBADTYPE"

.PP
Definition at line 126 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_ebfile = NC_EBFILE"

.PP
Definition at line 115 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_echar = NC_ECHAR"

.PP
Definition at line 138 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_ecurl = NC_ECURL"

.PP
Definition at line 152 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_edap = NC_EDAP"

.PP
Definition at line 151 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_edapconstraint = NC_EDAPCONSTRAINT"

.PP
Definition at line 160 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_edapsvc = NC_EDAPSVC"

.PP
Definition at line 155 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_edapurl = NC_EDAPURL"

.PP
Definition at line 159 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_edas = NC_EDAS"

.PP
Definition at line 156 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_edatadds = NC_EDATADDS"

.PP
Definition at line 158 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_edds = NC_EDDS"

.PP
Definition at line 157 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_edimsize = NC_EDIMSIZE"

.PP
Definition at line 145 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_eedge = NC_EEDGE"

.PP
Definition at line 139 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_eexist = NC_EEXIST"

.PP
Definition at line 116 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_eglobal = NC_EGLOBAL"

.PP
Definition at line 131 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_eindefine = NC_EINDEFINE"

.PP
Definition at line 120 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_einval = NC_EINVAL"

.PP
Definition at line 117 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_einvalcoords = NC_EINVALCOORDS"

.PP
Definition at line 121 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_eio = NC_EIO"

.PP
Definition at line 153 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_emaxatts = NC_EMAXATTS"

.PP
Definition at line 125 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_emaxdims = NC_EMAXDIMS"

.PP
Definition at line 122 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_emaxname = NC_EMAXNAME"

.PP
Definition at line 134 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_emaxvars = NC_EMAXVARS"

.PP
Definition at line 129 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_enameinuse = NC_ENAMEINUSE"

.PP
Definition at line 123 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_enodata = NC_ENODATA"

.PP
Definition at line 154 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_enomem = NC_ENOMEM"

.PP
Definition at line 143 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_enorecvars = NC_ENORECVARS"

.PP
Definition at line 136 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_enotatt = NC_ENOTATT"

.PP
Definition at line 124 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_enotindefine = NC_ENOTINDEFINE"

.PP
Definition at line 119 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_enotnc = NC_ENOTNC"

.PP
Definition at line 132 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_enotvar = NC_ENOTVAR"

.PP
Definition at line 130 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_eperm = NC_EPERM"

.PP
Definition at line 118 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_erange = NC_ERANGE"

.PP
Definition at line 142 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_estride = NC_ESTRIDE"

.PP
Definition at line 140 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_ests = NC_ESTS"

.PP
Definition at line 133 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_etranslation = NC_ETRANSLATION"

.PP
Definition at line 161 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_etrunc = NC_ETRUNC"

.PP
Definition at line 146 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_eunlimit = NC_EUNLIMIT"

.PP
Definition at line 135 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_eunlimpos = NC_EUNLIMPOS"

.PP
Definition at line 128 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_evarsize = NC_EVARSIZE"

.PP
Definition at line 144 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_exdr = NC_EXDR"

.PP
Definition at line 113 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_fatal = NC_FATAL"

.PP
Definition at line 165 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_fill = NC_FILL"

.PP
Definition at line 81 of file module_netcdf_nf_data\&.F90\&.
.SS "integer(ik1), parameter netcdf_nf_data::nf_fill_byte = NC_FILL_BYTE"

.PP
Definition at line 65 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_fill_char = IACHAR(NC_FILL_CHAR)"

.PP
Definition at line 64 of file module_netcdf_nf_data\&.F90\&.
.SS "real(rk8), parameter netcdf_nf_data::nf_fill_double = NC_FILL_DOUBLE"

.PP
Definition at line 72 of file module_netcdf_nf_data\&.F90\&.
.SS "real(rk4), parameter netcdf_nf_data::nf_fill_float = NC_FILL_FLOAT"

.PP
Definition at line 69 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_fill_int = NC_FILL_INT"

.PP
Definition at line 67 of file module_netcdf_nf_data\&.F90\&.
.SS "real(rk4), parameter netcdf_nf_data::nf_fill_real = NF_FILL_FLOAT"

.PP
Definition at line 70 of file module_netcdf_nf_data\&.F90\&.
.SS "real(rk4), parameter netcdf_nf_data::nf_fill_real4 = NF_FILL_FLOAT"

.PP
Definition at line 71 of file module_netcdf_nf_data\&.F90\&.
.SS "real(rk8), parameter netcdf_nf_data::nf_fill_real8 = NF_FILL_DOUBLE"

.PP
Definition at line 73 of file module_netcdf_nf_data\&.F90\&.
.SS "integer(ik2), parameter netcdf_nf_data::nf_fill_short = NC_FILL_SHORT"

.PP
Definition at line 66 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_float = NC_FLOAT"

.PP
Definition at line 58 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_format_64bit = NC_FORMAT_64BIT"

.PP
Definition at line 90 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_format_classic = NC_FORMAT_CLASSIC"

.PP
Definition at line 89 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_global = NC_GLOBAL"

.PP
Definition at line 98 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_inmemory = NC_INMEMORY"

.PP
Definition at line 93 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_int = NC_INT"

.PP
Definition at line 57 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_int1 = NF_BYTE"

.PP
Definition at line 53 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_int2 = NF_SHORT"

.PP
Definition at line 56 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_lock = NC_LOCK"

.PP
Definition at line 83 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_max_attrs = NC_MAX_ATTRS"

.PP
Definition at line 103 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_max_dims = NC_MAX_DIMS"

.PP
Definition at line 102 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_max_name = NC_MAX_NAME"

.PP
Definition at line 105 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_max_var_dims = NC_MAX_DIMS"

.PP
Definition at line 106 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_max_vars = NC_MAX_VARS"

.PP
Definition at line 104 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_mmap = NC_MMAP"

.PP
Definition at line 92 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_nat = NC_NAT"

.PP
Definition at line 51 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_noclobber = NC_NOCLOBBER"

.PP
Definition at line 80 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_noerr = NC_NOERR"

.PP
Definition at line 110 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_nofill = NC_NOFILL"

.PP
Definition at line 82 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_nowrite = NC_NOWRITE"

.PP
Definition at line 77 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_real = NF_FLOAT"

.PP
Definition at line 59 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_share = NC_SHARE"

.PP
Definition at line 84 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_short = NC_SHORT"

.PP
Definition at line 55 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_sizehint_default = NC_SIZEHINT_DEFAULT"

.PP
Definition at line 87 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_strict_nc3 = NC_STRICT_NC3"

.PP
Definition at line 85 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_syserr = NC_SYSERR"

.PP
Definition at line 112 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_unlimited = NC_UNLIMITED"

.PP
Definition at line 97 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_verbose = NC_VERBOSE"

.PP
Definition at line 166 of file module_netcdf_nf_data\&.F90\&.
.SS "integer, parameter netcdf_nf_data::nf_write = NC_WRITE"

.PP
Definition at line 78 of file module_netcdf_nf_data\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
