.TH "netcdf4_nc_interfaces::nc_set_chunk_cache" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nc_interfaces::nc_set_chunk_cache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_set_chunk_cache\fP (size, nelems, preemption)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1172 of file module_netcdf4_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf4_nc_interfaces::nc_set_chunk_cache::nc_set_chunk_cache (integer(c_size_t), value size, integer(c_size_t), value nelems, real(c_float), value preemption)"

.PP
Definition at line 1173 of file module_netcdf4_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
