.TH "netcdf_nc_interfaces::nc_sync" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_sync
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_sync\fP (ncid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 263 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_sync::nc_sync (integer(c_int), value ncid)"

.PP
Definition at line 264 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
