.TH "netcdf_fortv2_c_interfaces::c_ncvp1c" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_fortv2_c_interfaces::c_ncvp1c
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBc_ncvp1c\fP (ncid, varid, indices, value, rcode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 290 of file module_netcdf_fortv2_c_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "subroutine netcdf_fortv2_c_interfaces::c_ncvp1c::c_ncvp1c (integer(c_int), value ncid, integer(c_int), value varid, type(c_ptr), value indices, character(kind=c_char), dimension(*), intent(in) value, integer(c_int), intent(out) rcode)"

.PP
Definition at line 291 of file module_netcdf_fortv2_c_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
