.TH "netcdf4_nf_interfaces::nf_inq_type" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf4_nf_interfaces::nf_inq_type
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_type\fP (ncid, xtype, name, isize)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 260 of file module_netcdf4_nf_interfaces\&.F90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer function netcdf4_nf_interfaces::nf_inq_type::nf_inq_type (integer, intent(in) ncid, integer, intent(in) xtype, character(len=*), intent(in) name, integer, intent(out) isize)"

.PP
Definition at line 261 of file module_netcdf4_nf_interfaces\&.F90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
