.TH "netcdf_nc_interfaces::nc_open_mem" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces::nc_open_mem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "integer(c_int) function \fBnc_open_mem\fP (path, mode, size, memory, ncid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "integer(c_int) function netcdf_nc_interfaces::nc_open_mem::nc_open_mem (character(kind=c_char), dimension(*), intent(in) path, integer(c_int), value mode, integer(c_size_t), value size, type(c_ptr), value memory, integer(c_int), intent(out) ncid)"

.PP
Definition at line 183 of file module_netcdf_nc_interfaces\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
