.TH "netcdf_nc_interfaces" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netcdf_nc_interfaces
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBaddcnullchar\fP"
.br
.RI "module procedure interfaces for utility routines "
.ti -1c
.RI "interface \fBnc__create\fP"
.br
.ti -1c
.RI "interface \fBnc__create_mp\fP"
.br
.ti -1c
.RI "interface \fBnc__enddef\fP"
.br
.ti -1c
.RI "interface \fBnc__open\fP"
.br
.ti -1c
.RI "interface \fBnc__open_mp\fP"
.br
.ti -1c
.RI "interface \fBnc_abort\fP"
.br
.ti -1c
.RI "interface \fBnc_close\fP"
.br
.ti -1c
.RI "interface \fBnc_copy_att\fP"
.br
.ti -1c
.RI "interface \fBnc_copy_var\fP"
.br
.ti -1c
.RI "interface \fBnc_create\fP"
.br
.ti -1c
.RI "interface \fBnc_def_dim\fP"
.br
.ti -1c
.RI "interface \fBnc_def_var\fP"
.br
.ti -1c
.RI "interface \fBnc_del_att\fP"
.br
.ti -1c
.RI "interface \fBnc_delete\fP"
.br
.ti -1c
.RI "interface \fBnc_delete_mp\fP"
.br
.ti -1c
.RI "interface \fBnc_enddef\fP"
.br
.ti -1c
.RI "interface \fBnc_get_att_double\fP"
.br
.ti -1c
.RI "interface \fBnc_get_att_float\fP"
.br
.ti -1c
.RI "interface \fBnc_get_att_int\fP"
.br
.ti -1c
.RI "interface \fBnc_get_att_long\fP"
.br
.ti -1c
.RI "interface \fBnc_get_att_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_att_short\fP"
.br
.ti -1c
.RI "interface \fBnc_get_att_text\fP"
.br
.ti -1c
.RI "interface \fBnc_get_att_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1_double\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1_float\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1_int\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1_long\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1_short\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1_text\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var1_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_double\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_float\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_int\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_long\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_short\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_text\fP"
.br
.ti -1c
.RI "interface \fBnc_get_var_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara_double\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara_float\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara_int\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara_long\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara_short\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara_text\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vara_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_varm_double\fP"
.br
.ti -1c
.RI "interface \fBnc_get_varm_float\fP"
.br
.ti -1c
.RI "interface \fBnc_get_varm_int\fP"
.br
.ti -1c
.RI "interface \fBnc_get_varm_long\fP"
.br
.ti -1c
.RI "interface \fBnc_get_varm_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_varm_short\fP"
.br
.ti -1c
.RI "interface \fBnc_get_varm_text\fP"
.br
.ti -1c
.RI "interface \fBnc_get_varm_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars_double\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars_float\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars_int\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars_long\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars_short\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars_text\fP"
.br
.ti -1c
.RI "interface \fBnc_get_vars_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_inq\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_att\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_attid\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_attlen\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_attname\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_atttype\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_base_pe\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_dim\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_dimid\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_dimlen\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_dimname\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_format\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_libvers\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_natts\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_ndims\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_nvars\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_path\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_unlimdim\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_var\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_vardimid\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_varid\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_varname\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_varnatts\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_varndims\fP"
.br
.ti -1c
.RI "interface \fBnc_inq_vartype\fP"
.br
.ti -1c
.RI "interface \fBnc_open\fP"
.br
.ti -1c
.RI "interface \fBnc_open_mem\fP"
.br
.ti -1c
.RI "interface \fBnc_put_att_double\fP"
.br
.ti -1c
.RI "interface \fBnc_put_att_float\fP"
.br
.ti -1c
.RI "interface \fBnc_put_att_int\fP"
.br
.ti -1c
.RI "interface \fBnc_put_att_long\fP"
.br
.ti -1c
.RI "interface \fBnc_put_att_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_att_short\fP"
.br
.ti -1c
.RI "interface \fBnc_put_att_text\fP"
.br
.ti -1c
.RI "interface \fBnc_put_att_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1_double\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1_float\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1_int\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1_long\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1_short\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1_text\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var1_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var_double\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var_float\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var_int\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var_long\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var_short\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var_text\fP"
.br
.ti -1c
.RI "interface \fBnc_put_var_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara_double\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara_float\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara_int\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara_long\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara_short\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara_text\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vara_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_varm_double\fP"
.br
.ti -1c
.RI "interface \fBnc_put_varm_float\fP"
.br
.ti -1c
.RI "interface \fBnc_put_varm_int\fP"
.br
.ti -1c
.RI "interface \fBnc_put_varm_long\fP"
.br
.ti -1c
.RI "interface \fBnc_put_varm_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_varm_short\fP"
.br
.ti -1c
.RI "interface \fBnc_put_varm_text\fP"
.br
.ti -1c
.RI "interface \fBnc_put_varm_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars_double\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars_float\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars_int\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars_long\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars_schar\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars_short\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars_text\fP"
.br
.ti -1c
.RI "interface \fBnc_put_vars_uchar\fP"
.br
.ti -1c
.RI "interface \fBnc_redef\fP"
.br
.ti -1c
.RI "interface \fBnc_rename_att\fP"
.br
.ti -1c
.RI "interface \fBnc_rename_dim\fP"
.br
.ti -1c
.RI "interface \fBnc_rename_var\fP"
.br
.ti -1c
.RI "interface \fBnc_set_base_pe\fP"
.br
.ti -1c
.RI "interface \fBnc_set_default_format\fP"
.br
.ti -1c
.RI "interface \fBnc_set_fill\fP"
.br
.ti -1c
.RI "interface \fBnc_strerror\fP"
.br
.RI "Begin explicit interfaces for base nc_ functions\&. "
.ti -1c
.RI "interface \fBnc_sync\fP"
.br
.ti -1c
.RI "interface \fBstripcnullchar\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "character(len=(len(string)+1)) function \fBaddcnullchar\fP (string, nlen)"
.br
.ti -1c
.RI "character(len=nlen) function \fBstripcnullchar\fP (cstring, nlen)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "character(len=(len(string)+1)) function \fBnetcdf_nc_interfaces::addcnullchar\fP (character(len=*), intent(in) string, integer, intent(inout) nlen)"

.PP
Definition at line 2271 of file module_netcdf_nc_interfaces\&.f90\&.
.SS "character(len=nlen) function \fBnetcdf_nc_interfaces::stripcnullchar\fP (character(len=*), intent(in) cstring, integer, intent(in) nlen)"

.PP
Definition at line 2313 of file module_netcdf_nc_interfaces\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
