.TH "nf90_get_att" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nf90_get_att
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnf90_get_att_text\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_onebyteint\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_twobyteint\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_fourbyteint\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_eightbyteint\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_fourbytereal\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_eightbytereal\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_one_onebyteint\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_one_twobyteint\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_one_fourbyteint\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_one_eightbyteint\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_one_fourbytereal\fP"
.br
.ti -1c
.RI "\fBnf90_get_att_one_eightbytereal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file netcdf_overloads\&.f90\&.
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "nf90_get_att::nf90_get_att_eightbyteint ()"

.SS "nf90_get_att::nf90_get_att_eightbytereal ()"

.SS "nf90_get_att::nf90_get_att_fourbyteint ()"

.SS "nf90_get_att::nf90_get_att_fourbytereal ()"

.SS "nf90_get_att::nf90_get_att_one_eightbyteint ()"

.SS "nf90_get_att::nf90_get_att_one_eightbytereal ()"

.SS "nf90_get_att::nf90_get_att_one_fourbyteint ()"

.SS "nf90_get_att::nf90_get_att_one_fourbytereal ()"

.SS "nf90_get_att::nf90_get_att_one_onebyteint ()"

.SS "nf90_get_att::nf90_get_att_one_twobyteint ()"

.SS "nf90_get_att::nf90_get_att_onebyteint ()"

.SS "nf90_get_att::nf90_get_att_text ()"

.SS "nf90_get_att::nf90_get_att_twobyteint ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
