.TH "nf_attio.F90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nf_attio.F90
.SH SYNOPSIS
.br
.PP
\fC#include 'nfconfig\&.inc'\fP
.br

.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnf_put_att_text\fP (ncid, varid, name, nlen, text)"
.br
.ti -1c
.RI "integer function \fBnf_put_att_text_a\fP (ncid, varid, name, nlen, text)"
.br
.ti -1c
.RI "function \fBnf_put_att_int1\fP (ncid, varid, name, xtype, nlen, i1vals)"
.br
.ti -1c
.RI "function \fBnf_put_att_int2\fP (ncid, varid, name, xtype, nlen, i2vals)"
.br
.ti -1c
.RI "function \fBnf_put_att_int\fP (ncid, varid, name, xtype, nlen, ivals)"
.br
.ti -1c
.RI "function \fBnf_put_att_real\fP (ncid, varid, name, xtype, nlen, rvals)"
.br
.ti -1c
.RI "function \fBnf_put_att_double\fP (ncid, varid, name, xtype, nlen, dvals)"
.br
.ti -1c
.RI "integer function \fBnf_get_att_text\fP (ncid, varid, name, text)"
.br
.ti -1c
.RI "integer function \fBnf_get_att_text_a\fP (ncid, varid, name, text)"
.br
.ti -1c
.RI "integer function \fBnf_get_att_int1\fP (ncid, varid, name, i1vals)"
.br
.ti -1c
.RI "integer function \fBnf_get_att_int2\fP (ncid, varid, name, i2vals)"
.br
.ti -1c
.RI "integer function \fBnf_get_att_int\fP (ncid, varid, name, ivals)"
.br
.ti -1c
.RI "integer function \fBnf_get_att_real\fP (ncid, varid, name, rvals)"
.br
.ti -1c
.RI "integer function \fBnf_get_att_double\fP (ncid, varid, name, dvals)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function nf_get_att_double (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, real(rk8), dimension(*), intent(out) dvals)"

.PP
Definition at line 528 of file nf_attio\&.F90\&.
.SS "integer function nf_get_att_int (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer(nfint), dimension(*), intent(out) ivals)"

.PP
Definition at line 460 of file nf_attio\&.F90\&.
.SS "integer function nf_get_att_int1 (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer(nfint1), dimension(*), intent(out) i1vals)"

.PP
Definition at line 376 of file nf_attio\&.F90\&.
.SS "integer function nf_get_att_int2 (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer(nfint2), dimension(*), intent(out) i2vals)"

.PP
Definition at line 419 of file nf_attio\&.F90\&.
.SS "integer function nf_get_att_real (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, real(nfreal), dimension(*), intent(out) rvals)"

.PP
Definition at line 494 of file nf_attio\&.F90\&.
.SS "integer function nf_get_att_text (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, character(len=*), intent(out) text)"

.PP
Definition at line 312 of file nf_attio\&.F90\&.
.SS "integer function nf_get_att_text_a (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, character(len=1), dimension(*), intent(out) text)"

.PP
Definition at line 344 of file nf_attio\&.F90\&.
.SS "function nf_put_att_double (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(in) xtype, integer, intent(in) nlen, real(rk8), dimension(*), intent(in) dvals)"

.PP
Definition at line 281 of file nf_attio\&.F90\&.
.SS "function nf_put_att_int (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(in) xtype, integer, intent(in) nlen, integer(nfint), dimension(*), intent(in) ivals)"

.PP
Definition at line 201 of file nf_attio\&.F90\&.
.SS "function nf_put_att_int1 (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(in) xtype, integer, intent(in) nlen, integer(nfint1), dimension(*), intent(in) i1vals)"

.PP
Definition at line 104 of file nf_attio\&.F90\&.
.SS "function nf_put_att_int2 (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(in) xtype, integer, intent(in) nlen, integer(nfint2), dimension(*), intent(in) i2vals)"

.PP
Definition at line 155 of file nf_attio\&.F90\&.
.SS "function nf_put_att_real (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(in) xtype, integer, intent(in) nlen, real(nfreal), dimension(*), intent(in) rvals)"

.PP
Definition at line 241 of file nf_attio\&.F90\&.
.SS "integer function nf_put_att_text (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(in) nlen, character(len=*), intent(in) text)"

.PP
Definition at line 35 of file nf_attio\&.F90\&.
.SS "integer function nf_put_att_text_a (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(in) nlen, character(len=1), dimension(*), intent(in) text)"

.PP
Definition at line 66 of file nf_attio\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
