.TH "nf_genatt.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nf_genatt.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq_att\fP (ncid, varid, name, xtype, nlen)"
.br
.ti -1c
.RI "integer function \fBnf_inq_atttype\fP (ncid, varid, name, xtype)"
.br
.ti -1c
.RI "integer function \fBnf_inq_attlen\fP (ncid, varid, name, nlen)"
.br
.ti -1c
.RI "integer function \fBnf_inq_attid\fP (ncid, varid, name, attnum)"
.br
.ti -1c
.RI "integer function \fBnf_inq_attname\fP (ncid, varid, attnum, name)"
.br
.ti -1c
.RI "integer function \fBnf_copy_att\fP (ncid_in, varid_in, name, ncid_out, varid_out)"
.br
.ti -1c
.RI "integer function \fBnf_rename_att\fP (ncid, varid, name, newname)"
.br
.ti -1c
.RI "integer function \fBnf_del_att\fP (ncid, varid, name)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function nf_copy_att (integer, intent(in) ncid_in, integer, intent(in) varid_in, character(len=*), intent(in) name, integer, intent(in) ncid_out, integer, intent(in) varid_out)"

.PP
Definition at line 211 of file nf_genatt\&.f90\&.
.SS "integer function nf_del_att (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name)"

.PP
Definition at line 279 of file nf_genatt\&.f90\&.
.SS "integer function nf_inq_att (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(out) xtype, integer, intent(out) nlen)"

.PP
Definition at line 33 of file nf_genatt\&.f90\&.
.SS "integer function nf_inq_attid (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(out) attnum)"

.PP
Definition at line 140 of file nf_genatt\&.f90\&.
.SS "integer function nf_inq_attlen (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(out) nlen)"

.PP
Definition at line 105 of file nf_genatt\&.f90\&.
.SS "integer function nf_inq_attname (integer, intent(in) ncid, integer, intent(in) varid, integer, intent(in) attnum, character(len=*), intent(out) name)"

.PP
Definition at line 174 of file nf_genatt\&.f90\&.
.SS "integer function nf_inq_atttype (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, integer, intent(out) xtype)"

.PP
Definition at line 70 of file nf_genatt\&.f90\&.
.SS "integer function nf_rename_att (integer, intent(in) ncid, integer, intent(in) varid, character(len=*), intent(in) name, character(len=*), intent(in) newname)"

.PP
Definition at line 245 of file nf_genatt\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
