.TH "nf_geninq.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nf_geninq.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBnf_inq\fP (ncid, ndims, nvars, ngatts, unlimdimid)"
.br
.ti -1c
.RI "integer function \fBnf_inq_ndims\fP (ncid, ndims)"
.br
.ti -1c
.RI "integer function \fBnf_inq_nvars\fP (ncid, nvars)"
.br
.ti -1c
.RI "integer function \fBnf_inq_natts\fP (ncid, ngatts)"
.br
.ti -1c
.RI "integer function \fBnf_inq_unlimdim\fP (ncid, unlimdimid)"
.br
.ti -1c
.RI "integer function \fBnf_inq_format\fP (ncid, format_type)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function nf_inq (integer, intent(in) ncid, integer, intent(out) ndims, integer, intent(out) nvars, integer, intent(out) ngatts, integer, intent(out) unlimdimid)"

.PP
Definition at line 34 of file nf_geninq\&.f90\&.
.SS "integer function nf_inq_format (integer, intent(in) ncid, integer, intent(out) format_type)"

.PP
Definition at line 182 of file nf_geninq\&.f90\&.
.SS "integer function nf_inq_natts (integer, intent(in) ncid, integer, intent(out) ngatts)"

.PP
Definition at line 124 of file nf_geninq\&.f90\&.
.SS "integer function nf_inq_ndims (integer, intent(in) ncid, integer, intent(out) ndims)"

.PP
Definition at line 72 of file nf_geninq\&.f90\&.
.SS "integer function nf_inq_nvars (integer, intent(in) ncid, integer, intent(out) nvars)"

.PP
Definition at line 98 of file nf_geninq\&.f90\&.
.SS "integer function nf_inq_unlimdim (integer, intent(in) ncid, integer, intent(out) unlimdimid)"

.PP
Definition at line 150 of file nf_geninq\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
