.TH "nf_misc.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nf_misc.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "character(len=80) function \fBnf_inq_libvers\fP ()"
.br
.ti -1c
.RI "character(len=80) function \fBnf_strerror\fP (ncerr)"
.br
.ti -1c
.RI "logical function \fBnf_issyserr\fP (nerr)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "character(len=80) function nf_inq_libvers ()"

.PP
Definition at line 32 of file nf_misc\&.f90\&.
.SS "logical function nf_issyserr (integer, intent(in) nerr)"

.PP
Definition at line 125 of file nf_misc\&.f90\&.
.SS "character(len=80) function nf_strerror (integer(kind=c_int), intent(in) ncerr)"

.PP
Definition at line 77 of file nf_misc\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
