.TH "nf_varsio.F90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nf_varsio.F90
.SH SYNOPSIS
.br
.PP
\fC#include 'nfconfig\&.inc'\fP
.br

.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "function \fBnf_put_vars_text\fP (ncid, varid, start, counts, strides, text)"
.br
.ti -1c
.RI "function \fBnf_put_vars_text_a\fP (ncid, varid, start, counts, strides, text)"
.br
.ti -1c
.RI "function \fBnf_put_vars_int1\fP (ncid, varid, start, counts, strides, i1vals)"
.br
.ti -1c
.RI "function \fBnf_put_vars_int2\fP (ncid, varid, start, counts, strides, i2vals)"
.br
.ti -1c
.RI "function \fBnf_put_vars_int\fP (ncid, varid, start, counts, strides, ivals)"
.br
.ti -1c
.RI "function \fBnf_put_vars_real\fP (ncid, varid, start, counts, strides, rvals)"
.br
.ti -1c
.RI "function \fBnf_put_vars_double\fP (ncid, varid, start, counts, strides, dvals)"
.br
.ti -1c
.RI "function \fBnf_put_vars\fP (ncid, varid, start, counts, strides, values)"
.br
.ti -1c
.RI "function \fBnf_get_vars_text\fP (ncid, varid, start, counts, strides, text)"
.br
.ti -1c
.RI "function \fBnf_get_vars_text_a\fP (ncid, varid, start, counts, strides, text)"
.br
.ti -1c
.RI "function \fBnf_get_vars_int1\fP (ncid, varid, start, counts, strides, i1vals)"
.br
.ti -1c
.RI "function \fBnf_get_vars_int2\fP (ncid, varid, start, counts, strides, i2vals)"
.br
.ti -1c
.RI "function \fBnf_get_vars_int\fP (ncid, varid, start, counts, strides, ivals)"
.br
.ti -1c
.RI "function \fBnf_get_vars_real\fP (ncid, varid, start, counts, strides, rvals)"
.br
.ti -1c
.RI "function \fBnf_get_vars_double\fP (ncid, varid, start, counts, strides, dvals)"
.br
.ti -1c
.RI "function \fBnf_get_vars\fP (ncid, varid, start, counts, strides, values)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "function nf_get_vars (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, character(kind=c_char), intent(inout) values)"

.PP
Definition at line 1040 of file nf_varsio\&.F90\&.
.SS "function nf_get_vars_double (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, real(rk8), dimension(*), intent(out) dvals)"

.PP
Definition at line 976 of file nf_varsio\&.F90\&.
.SS "function nf_get_vars_int (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, integer(nfint), dimension(*), intent(out) ivals)"

.PP
Definition at line 842 of file nf_varsio\&.F90\&.
.SS "function nf_get_vars_int1 (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, integer(nfint1), dimension(*), intent(out) i1vals)"

.PP
Definition at line 689 of file nf_varsio\&.F90\&.
.SS "function nf_get_vars_int2 (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, integer(nfint2), dimension(*), intent(out) i2vals)"

.PP
Definition at line 767 of file nf_varsio\&.F90\&.
.SS "function nf_get_vars_real (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, real(nfreal), dimension(*), intent(out) rvals)"

.PP
Definition at line 909 of file nf_varsio\&.F90\&.
.SS "function nf_get_vars_text (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, character(len=*), intent(out) text)"

.PP
Definition at line 564 of file nf_varsio\&.F90\&.
.SS "function nf_get_vars_text_a (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, character(len=1), dimension(*), intent(out) text)"

.PP
Definition at line 627 of file nf_varsio\&.F90\&.
.SS "function nf_put_vars (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, character(kind=c_char), dimension(*), intent(in), target values)"

.PP
Definition at line 501 of file nf_varsio\&.F90\&.
.SS "function nf_put_vars_double (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, real(rk8), dimension(*), intent(in) dvals)"

.PP
Definition at line 437 of file nf_varsio\&.F90\&.
.SS "function nf_put_vars_int (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, integer(nfint), dimension(*), intent(in) ivals)"

.PP
Definition at line 303 of file nf_varsio\&.F90\&.
.SS "function nf_put_vars_int1 (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, integer(nfint1), dimension(*), intent(in) i1vals)"

.PP
Definition at line 150 of file nf_varsio\&.F90\&.
.SS "function nf_put_vars_int2 (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, integer(nfint2), dimension(*), intent(in) i2vals)"

.PP
Definition at line 228 of file nf_varsio\&.F90\&.
.SS "function nf_put_vars_real (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, real(nfreal), dimension(*), intent(in) rvals)"

.PP
Definition at line 370 of file nf_varsio\&.F90\&.
.SS "function nf_put_vars_text (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, character(len=*), intent(in) text)"

.PP
Definition at line 44 of file nf_varsio\&.F90\&.
.SS "function nf_put_vars_text_a (integer, intent(in) ncid, integer, intent(in) varid, integer, dimension(*), intent(in) start, integer, dimension(*), intent(in) counts, integer, dimension(*), intent(in) strides, character(len=1), dimension(*), intent(in) text)"

.PP
Definition at line 98 of file nf_varsio\&.F90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
