.TH "testEightByteGet.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testEightByteGet.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBtesteightbyteget\fP"
.br
.ti -1c
.RI "subroutine \fBcheck\fP (status)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine testeightbyteget::check (integer, intent(in) status)"

.PP
Definition at line 43 of file testEightByteGet\&.f90\&.
.SS "program testeightbyteget ()"

.PP
Definition at line 1 of file testEightByteGet\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
