.TH "typeSizes.f90" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typeSizes.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBtypesizes\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "logical function \fBtypesizes::bytesizesok\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBtypesizes::onebyteint\fP = selected_int_kind(2)"
.br
.ti -1c
.RI "integer, parameter \fBtypesizes::twobyteint\fP = selected_int_kind(4)"
.br
.ti -1c
.RI "integer, parameter \fBtypesizes::fourbyteint\fP = selected_int_kind(9)"
.br
.ti -1c
.RI "integer, parameter \fBtypesizes::eightbyteint\fP = selected_int_kind(18)"
.br
.ti -1c
.RI "integer, parameter \fBtypesizes::fourbytereal\fP = selected_real_kind(P = 6, R = 37)"
.br
.ti -1c
.RI "integer, parameter \fBtypesizes::eightbytereal\fP = selected_real_kind(P = 13, R = 307)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
