.TH "typesizes" 3 "Wed Jan 17 2018" "Version 4.5.0-development" "NetCDF-Fortran" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typesizes
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "logical function \fBbytesizesok\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBonebyteint\fP = selected_int_kind(2)"
.br
.ti -1c
.RI "integer, parameter \fBtwobyteint\fP = selected_int_kind(4)"
.br
.ti -1c
.RI "integer, parameter \fBfourbyteint\fP = selected_int_kind(9)"
.br
.ti -1c
.RI "integer, parameter \fBeightbyteint\fP = selected_int_kind(18)"
.br
.ti -1c
.RI "integer, parameter \fBfourbytereal\fP = selected_real_kind(P = 6, R = 37)"
.br
.ti -1c
.RI "integer, parameter \fBeightbytereal\fP = selected_real_kind(P = 13, R = 307)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "logical function typesizes::bytesizesok ()"

.PP
Definition at line 43 of file typeSizes\&.f90\&.
.SH "Variable Documentation"
.PP 
.SS "integer, parameter typesizes::eightbyteint = selected_int_kind(18)"

.PP
Definition at line 33 of file typeSizes\&.f90\&.
.SS "integer, parameter typesizes::eightbytereal = selected_real_kind(P = 13, R = 307)"

.PP
Definition at line 38 of file typeSizes\&.f90\&.
.SS "integer, parameter typesizes::fourbyteint = selected_int_kind(9)"

.PP
Definition at line 33 of file typeSizes\&.f90\&.
.SS "integer, parameter typesizes::fourbytereal = selected_real_kind(P = 6, R = 37)"

.PP
Definition at line 38 of file typeSizes\&.f90\&.
.SS "integer, parameter typesizes::onebyteint = selected_int_kind(2)"

.PP
Definition at line 33 of file typeSizes\&.f90\&.
.SS "integer, parameter typesizes::twobyteint = selected_int_kind(4)"

.PP
Definition at line 33 of file typeSizes\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF-Fortran from the source code\&.
