###
# Run a docker-based test of tests.
#
# See https://github.com/Unidata/docker-nctests
# How    https://github.com/WardF/netcdf-test-action

on: [pull_request,workflow_dispatch]

concurrency:  
  group: ${{ github.workflow}}-${{ github.head_ref }}  
  cancel-in-progress: true

permissions: {} 

jobs:  
  netcdf-tests-serial:
    name: Docker-Based NetCDF-C, Fortran Regression Testing (Serial)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo-type: [ 'fortran' ]
        c-branch: [ 'v4.9.3' ]
        h5ver: [ '1.12.1', '1.14.6' ]
        c-compiler: [ 'gcc', 'clang' ]
        buildsystem: [ 'both' ]

    steps:
      - uses: actions/checkout@v4
      - name: Pull and Run netCDF Regression Tests
        uses: WardF/netcdf-test-action@v1
        with:
          repo-type: '${{ matrix.repo-type }}'
          run-c: 'FALSE'
          build-system: '${{ matrix.buildsystem }}'
          hdf5-version: '${{ matrix.h5ver }}'
          ctest-repeat: 3
          c-compiler: '${{ matrix.c-compiler }}'
          c-branch: '${{ matrix.c-branch }}'
          run-fortran: 'TRUE'

  netcdf-tests-parallel:

    needs: netcdf-tests-serial

    name: Docker-Based NetCDF-C, Fortran Regression Testing (Parallel)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo-type: [ 'fortran' ]
        c-branch: [ 'v4.9.3' ]
        h5ver: [ '1.14.6' ]
        c-compiler: [ 'mpicc' ]
        mpich-version: [ '4.3.0' ]
        buildsystem: [ 'cmake', 'autotools' ]

    steps:
      - uses: actions/checkout@v4
      - name: Pull and Run netCDF Regression Tests
        uses: WardF/netcdf-test-action@v1
        with:
          repo-type: '${{ matrix.repo-type }}'
          run-c: 'FALSE'
          build-system: '${{ matrix.buildsystem }}'
          hdf5-version: '${{ matrix.h5ver }}'
          ctest-repeat: 3
          c-compiler: '${{ matrix.c-compiler }}'
          c-branch: '${{ matrix.c-branch }}'
          mpich-version: '${{ matrix.mpich-version }}'
          run-fortran: 'TRUE'

